# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "osmo-deps.credentialsSecretName" . }}
  labels:
    {{- include "osmo-deps.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.credentials.postgresqlPassword | quote }}
  redis-password: {{ .Values.credentials.valkeyPassword | quote }}
  access_key_id: {{ .Values.credentials.objectStorageAccessKeyId | quote }}
  access_key: {{ .Values.credentials.objectStorageAccessKey | quote }}
  object-storage.yaml: |
    access_key_id: {{ .Values.credentials.objectStorageAccessKeyId | quote }}
    access_key: {{ .Values.credentials.objectStorageAccessKey | quote }}
  admin-password: {{ .Values.credentials.adminPassword | quote }}
  mek.yaml: |
    {{- .Values.credentials.mek | nindent 4 }}
