# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
exports_files(["action.yaml"], visibility = ["//src/scripts/testbot/tests:__pkg__"])
