"""
SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
SPDX-License-Identifier: Apache-2.0
"""

load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "osmo_user_eval_test",
    srcs = ["osmo_user_eval_test.py"],
    data = ["//skills/osmo-user:eval_files"],
)
