# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: osmotaskgroups.workflow.osmo.nvidia.com
spec:
  group: workflow.osmo.nvidia.com
  names:
    kind: OSMOTaskGroup
    listKind: OSMOTaskGroupList
    plural: osmotaskgroups
    shortNames:
      - otg
    singular: osmotaskgroup
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Phase
          type: string
          jsonPath: .status.phase
        - name: Runtime
          type: string
          jsonPath: .spec.runtimeType
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                workflowID:
                  type: string
                workflowUUID:
                  type: string
                groupName:
                  type: string
                groupUUID:
                  type: string
                runtimeType:
                  type: string
                  default: kai
                  enum:
                    - kai
                runtimeConfig:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
              required:
                - runtimeConfig
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum:
                    - Pending
                    - Running
                    - Succeeded
                    - Failed
                    - Unknown
                message:
                  type: string
                podSummary:
                  type: object
                  properties:
                    pending:
                      type: integer
                      format: int32
                    running:
                      type: integer
                      format: int32
                    succeeded:
                      type: integer
                      format: int32
                    failed:
                      type: integer
                      format: int32
                    unknown:
                      type: integer
                      format: int32
                conditions:
                  type: array
                  items:
                    type: object
                    required:
                      - lastTransitionTime
                      - message
                      - reason
                      - status
                      - type
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      observedGeneration:
                        type: integer
                        format: int64
                      lastTransitionTime:
                        type: string
                        format: date-time
                      reason:
                        type: string
                      message:
                        type: string
                runtimeStatus:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
