# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

image:
  pullPolicy: IfNotPresent

exposure:
  mode: external
  baseUrl: http://osmo-gateway

external:
  postgresql:
    host: osmo-deps-postgresql
    port: 5432
    database: osmo
    username: postgres
  valkey:
    host: osmo-deps-valkey
    port: 6379
    database: 0
    tls:
      enabled: false
  objectStorage:
    endpoint: http://osmo-deps-rustfs:9000
    region: us-east-1
    buckets:
      workflows: osmo-workflows
      logs: osmo-logs
      apps: osmo-apps

secrets:
  postgresql:
    existingSecret: osmo-deps-credentials
  valkey:
    existingSecret: osmo-deps-credentials
  objectStorage:
    existingSecret: osmo-deps-credentials
  masterEncryptionKey:
    existingSecret: osmo-deps-credentials
  defaultAdmin:
    existingSecret: osmo-deps-credentials
    username: admin
    keys:
      password: admin-password

configuration:
  enabled: true
  workflow:
    labels_config: null
    backend_images:
      init: nvcr.io/nvidia/osmo/init-container:6.3.1
      client: nvcr.io/nvidia/osmo/client:6.3.1
    credential_config:
      disable_data_validation:
        - s3

services:
  api:
    autoscaling:
      minReplicas: 1
      maxReplicas: 1
    env: &rustfsEnvironment
      - name: AWS_ENDPOINT_URL_S3
        value: http://osmo-deps-rustfs:9000
      - name: AWS_S3_FORCE_PATH_STYLE
        value: "true"
      - name: AWS_DEFAULT_REGION
        value: us-east-1
  worker:
    autoscaling:
      minReplicas: 1
      maxReplicas: 1
    env: *rustfsEnvironment
  logger:
    autoscaling:
      minReplicas: 1
      maxReplicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 512Mi
    env: *rustfsEnvironment
  agent:
    autoscaling:
      minReplicas: 1
      maxReplicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 512Mi
    env: *rustfsEnvironment
  router:
    autoscaling:
      minReplicas: 1
      maxReplicas: 1

gateway:
  envoy:
    autoscaling:
      minReplicas: 1
      maxReplicas: 1
    service:
      type: ClusterIP
    defaultIdentity:
      user: admin
      roles: osmo-admin
      allowedPools: default
