# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.  # pylint: disable=line-too-long
# SPDX-License-Identifier: Apache-2.0
"""Create a pull request with AI-generated test files."""

import logging
import shlex

from testbot.state import TestbotState
from testbot.tools.shell import run_shell, run_shell_with_file

logger = logging.getLogger(__name__)


def _has_open_agent_pr() -> bool:
    """Check if there's already an open PR with the ai-generated label."""
    result = run_shell("gh pr list --label ai-generated --state open --json number --jq \"length\"")
    if result.returncode != 0:
        return False
    try:
        return int(result.stdout.strip()) > 0
    except ValueError:
        return False


def create_pr(state: TestbotState) -> TestbotState:
    """LangGraph node: create a git branch, commit generated tests, and open a PR."""
    if not state["generated_files"]:
        logger.info("No generated files passed validation and quality gate. Skipping PR.")
        return state

    if state.get("dry_run", False):
        logger.info("Dry run: would create PR with files: %s", state["generated_files"])
        return state

    if _has_open_agent_pr():
        logger.info("An ai-generated PR is already open. Skipping to avoid stacking PRs.")
        return state

    branch_name = state["branch_name"]

    # Create branch from current HEAD (includes testbot code when run on feature branch)
    result = run_shell(f"git checkout -b {shlex.quote(branch_name)}")
    if result.returncode != 0:
        return {**state, "errors": state["errors"] + [f"git checkout failed: {result.stderr}"]}

    # Stage all generated files and modified BUILD files
    quoted_files = " ".join(shlex.quote(f) for f in state["generated_files"])
    result = run_shell(f"git add {quoted_files}")
    if result.returncode != 0:
        return {**state, "errors": state["errors"] + [f"git add failed: {result.stderr}"]}
    run_shell("git add */tests/BUILD */tests/BUILD.bazel 2>/dev/null || true")

    # Build commit message
    target_files = [t.file_path for t in state["targets"]]
    generated_count = len(state["generated_files"])
    provider = state["provider"]
    commit_message = (
        f"Add AI-generated tests for {generated_count} files\n\n"
        f"Coverage targets: {', '.join(target_files)}\n"  # pylint: disable=inconsistent-quotes
        f"Generated by: testbot pipeline (provider: {provider})"
    )

    result = run_shell_with_file("git commit -F {}", commit_message)
    if result.returncode != 0:
        return {**state, "errors": state["errors"] + [f"git commit failed: {result.stderr}"]}

    # Push (force to overwrite stale branch from previous failed runs)
    result = run_shell(f"git push -u origin {shlex.quote(branch_name)} --force")
    if result.returncode != 0:
        return {**state, "errors": state["errors"] + [f"git push failed: {result.stderr}"]}

    # Create PR
    pr_title = build_pr_title(state)
    pr_body = build_pr_body(state)

    pr_cmd = f"gh pr create --title {shlex.quote(pr_title)} --body-file {{}} --label ai-generated --base main"
    result = run_shell_with_file(pr_cmd, pr_body)
    if result.returncode != 0 and "label" in result.stderr.lower():
        run_shell("gh label create ai-generated --description 'AI-generated PR' --color 7057ff")
        result = run_shell_with_file(pr_cmd, pr_body)

    pr_url = result.stdout.strip() if result.returncode == 0 else None
    errors = list(state["errors"])
    if result.returncode != 0:
        errors.append(f"gh pr create failed: {result.stderr}")

    return {**state, "pr_url": pr_url, "errors": errors}


def build_pr_title(state: TestbotState) -> str:
    """Build PR title from target file paths."""
    target_files = [t.file_path for t in state["targets"]]
    return f"[testbot] Add tests for {', '.join(target_files)}"


def build_pr_body(state: TestbotState) -> str:
    """Build PR body with issue reference and checklist (required by PR checks)."""
    generated_count = len(state["generated_files"])
    files_list = "\n".join(f"- `{f}`" for f in state["generated_files"])
    return (
        "## Summary\n\n"
        f"AI-generated tests targeting {generated_count} file(s) with low coverage.\n\n"
        "Issue - None\n\n"
        "## Files tested\n\n"
        f"{files_list}\n\n"
        "## Checklist\n\n"
        "- [x] I am familiar with the Contributing Guidelines\n"
        "- [x] New or existing tests cover these changes\n"
        "- [x] The documentation is up to date with these changes\n\n"
        "---\n"
        "Generated by testbot pipeline"
    )
