{{- if .Values.dispatcher.service.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "workflow-controller.fullname" . }}-dispatcher
  labels:
    {{- include "workflow-controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: dispatcher
spec:
  type: {{ .Values.dispatcher.service.type }}
  ports:
  - name: http
    port: {{ .Values.dispatcher.service.port }}
    targetPort: http
  selector:
    {{- include "workflow-controller.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: dispatcher
{{- end }}
