# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: Namespace
metadata:
  name: osmo-system
  labels:
    workflow.osmo.nvidia.com/managed: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: osmo-workflows
  labels:
    workflow.osmo.nvidia.com/managed: "true"
