{
 "title": "Backend Operator",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_node_info,cluster)"
    }
   },
   { "name": "operator_namespace", "label": "Operator Namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "workflow_namespace", "label": "Workflow Namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  { "title": "Backend Operator Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backend Operator Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{cluster=~\"$cluster\", namespace=\"$operator_namespace\", pod=~\".*backend-.*\", container!=\"otc-container\"}[1h])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Workflow Pods by Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\", namespace=\"$workflow_namespace\", phase=~\"Failed|Succeeded|Running|Pending\"}) by (phase)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(kube_pod_info{namespace=\"$workflow_namespace\"})",
     "legendFormat": "ALL"
    }
   ]
  },
  {
   "title": "Backend Worker CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$operator_namespace\",cluster=~\"$cluster\", pod=~\".*-backend-worker.*\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=\"$operator_namespace\", resource=\"cpu\", container=\"backend-worker\"}",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Backend Worker Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"$operator_namespace\",cluster=~\"$cluster\", pod=~\".*backend-worker.*\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=\"$operator_namespace\", resource=\"memory\", container=\"backend-worker\"}",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Backend Listener CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$operator_namespace\",cluster=~\"$cluster\", pod=~\".*backend-listener.*\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=\"$operator_namespace\", resource=\"cpu\", container=\"backend-listener\"}",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Backend Listener Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"$operator_namespace\",cluster=~\"$cluster\", pod=~\".*backend-listener.*\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=\"$operator_namespace\", resource=\"memory\", container=\"backend-listener\"}",
     "legendFormat": "limit"
    }
   ]
  },
  { "title": "Backend Agent Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Backend Listener Queues",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "backend_listener_queue_length{cluster=~\"$cluster\"}",
     "legendFormat": "{{queue_type}}"
    }
   ]
  },
  {
   "title": "Backend Listener Message Sent per Minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum by(event_type) (increase(backend_message_transmission_count{cluster=~\"$cluster\", exported_namespace=\"$workflow_namespace\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Messages Added to Queue Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum by(event_type) (increase(backend_listener_queue_event_count{cluster=~\"$cluster\",exported_namespace=\"$workflow_namespace\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection Errors to Kubernetes Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum by(event_type) (increase(event_watch_connection_error_count{cluster=\"$cluster\",exported_namespace=\"$workflow_namespace\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Listener Kubernetes Events Received Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum by(event_type) (increase(kb_event_watch_count{cluster=~\"$cluster\",exported_namespace=\"$workflow_namespace\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event Processing Time Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "sum by(event_type) (increase(event_processing_times_sum{cluster=~\"$cluster\", exported_namespace=\"$workflow_namespace\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Websocket Disconnections Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum by(event_type) (increase(websocket_disconnect_count{cluster=~\"$cluster\", exported_namespace=\"$workflow_namespace\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Job Average Execution Time (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "sum by(job_type) (increase(backend_job_execution_time_sum{cluster=~\"$cluster\",exported_namespace=\"$workflow_namespace\"}[1m])/increase(backend_job_execution_time_count{cluster=~\"$cluster\",exported_namespace=\"$workflow_namespace\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}