{
 "title": "Observability Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Envoy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Envoy - Requests / min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_rq{envoy_cluster_name=\"service\"}[1m]) * 60",
     "legendFormat": "{{pod}}-{{envoy_response_code}}"
    },
    {
     "expr": "avg(rate(envoy_cluster_upstream_rq{envoy_cluster_name=\"service\"}[1m]) * 60)",
     "legendFormat": "Average"
    },
    {
     "expr": "quantile(0.90, rate(envoy_cluster_upstream_rq{envoy_cluster_name=\"service\"}[1m]) * 60)",
     "legendFormat": "Quantile90"
    }
   ]
  },
  {
   "title": "Envoy - Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"service\"}[1m])) by (le, pod))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"service\"}[1m])) by (le, pod)))",
     "legendFormat": "Average"
    },
    {
     "expr": "quantile(0.90, histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"service\"}[1m])) by (le, pod)))",
     "legendFormat": "Quantile90"
    }
   ]
  },
  {
   "title": "Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service - Autoscaler",
     "type": "timeseries",
     "description": "Number of running logger instances",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "count(envoy_cluster_upstream_cx_active{envoy_cluster_name=\"service\", pod=~\"osmo-service.*\"})",
       "legendFormat": "Number of service pods"
      },
      { "expr": "count(kube_node_info)", "legendFormat": "Number of nodes" }
     ]
    },
    {
     "title": "Service - Active Connections",
     "type": "timeseries",
     "description": "Number of active HTTP and websocket connections to each service instance",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "envoy_cluster_upstream_cx_active{envoy_cluster_name=\"service\", pod=~\"osmo-service.*\"}",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "avg(envoy_cluster_upstream_cx_active{envoy_cluster_name=\"service\", pod=~\"osmo-service.*\"})",
       "legendFormat": "Average"
      },
      {
       "expr": "quantile(.90, envoy_cluster_upstream_cx_active{envoy_cluster_name=\"service\", pod=~\"osmo-service.*\"})",
       "legendFormat": "Quantile90"
      }
     ]
    },
    {
     "title": "Service - API requests / min",
     "type": "timeseries",
     "description": "Increase in service API request counts",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum by (http_target, http_method) (increase(http_server_duration_count{http_target=~'/.*'}[1m:]))",
       "legendFormat": "{{http_method}} {{http_target}}"
      }
     ]
    },
    {
     "title": "Service - Total time spent on each API call per second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by(http_target) (increase(http_server_duration_sum[1m])) / 60",
       "legendFormat": "{{http_method}} {{http_target}}"
      }
     ]
    },
    {
     "title": "Service - API Latency 50th Percentile",
     "type": "timeseries",
     "description": "Service API latency without Envoy (50th percentile)",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by(le, http_target, http_method) (rate(http_server_duration_bucket{http_target=~'/.*'}[1m0s])))",
       "legendFormat": "{{http_method}} {{http_target}}"
      }
     ]
    },
    {
     "title": "Service - API Latency 99th Percentile",
     "type": "timeseries",
     "description": "Service API latency without Envoy (99th percentile)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, http_target, http_method) (rate(http_server_duration_bucket{http_target=~'/.*'}[1m0s])))",
       "legendFormat": "{{http_method}} {{http_target}}"
      }
     ]
    },
    {
     "title": "Service - CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "sum by (pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"default\", pod=~\"osmo-service(.*)\", container!=\"\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "Avg(sum by (pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"default\", pod=~\"osmo-service(.*)\", container!=\"\"}))",
       "legendFormat": "Average"
      },
      {
       "expr": "avg(sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"default\", resource=\"cpu\", pod=~\"osmo-service(.*)\", container=\"osmo-service\"}) by (pod))",
       "legendFormat": "Requests"
      },
      {
       "expr": "Quantile(.90, sum by (pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"default\", pod=~\"osmo-service(.*)\", container!=\"\"}))",
       "legendFormat": "Quantile90"
      }
     ]
    },
    {
     "title": "Service - Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"default\", pod=~\"osmo-service(.*)\", container!=\"\", image!=\"\"}) by (pod)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"default\", pod=~\"osmo-service(.*)\", container!=\"\", image!=\"\"}) by (pod))",
       "legendFormat": "Average"
      },
      {
       "expr": "avg(sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"default\", resource=\"memory\", pod=~\"osmo-service(.*)\", container=\"osmo-service\"}) by (pod))",
       "legendFormat": "Limits"
      },
      {
       "expr": "quantile(.90 ,sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"default\", pod=~\"osmo-service(.*)\", container!=\"\", image!=\"\"}) by (pod))",
       "legendFormat": "Quantile90"
      }
     ]
    }
   ]
  },
  { "title": "Logger", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Logger - Autoscaler",
   "type": "timeseries",
   "description": "Number of running logger instances",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "count(envoy_cluster_upstream_cx_active{envoy_cluster_name=\"service\", pod=~\"osmo-logger-.*\"})",
     "legendFormat": "Number of Logger Pods"
    },
    { "expr": "count(kube_node_info)", "legendFormat": "Number of Nodes" }
   ]
  },
  {
   "title": "Logger - Active Connections",
   "type": "timeseries",
   "description": "Number of active HTTP and websocket connections to each instance of the logger",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "envoy_cluster_upstream_cx_active{envoy_cluster_name=\"service\", pod=~\"osmo-logger-.*\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(envoy_cluster_upstream_cx_active{envoy_cluster_name=\"service\", pod=~\"osmo-logger-.*\"})",
     "legendFormat": "Average"
    },
    {
     "expr": "quantile(0.90, envoy_cluster_upstream_cx_active{envoy_cluster_name=\"service\", pod=~\"osmo-logger-.*\"})",
     "legendFormat": "Quantile90"
    }
   ]
  },
  {
   "title": "Logger - CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by (pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"default\", pod=~\"osmo-logger(.*)\", container=\"osmo-logger\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(sum by (pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"default\", pod=~\"osmo-logger(.*)\", container=\"osmo-logger\"}))",
     "legendFormat": "Average"
    },
    {
     "expr": "avg(sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"default\", resource=\"cpu\", pod=~\"osmo-logger(.*)\", container=\"osmo-logger\"})by (pod))",
     "legendFormat": "Requests"
    },
    {
     "expr": "quantile(0.90, sum by (pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"default\", pod=~\"osmo-logger(.*)\", container=\"osmo-logger\"}))",
     "legendFormat": "Quantile90"
    }
   ]
  },
  {
   "title": "Logger - Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", namespace=\"default\", pod=~\"osmo-logger(.*)\", container=\"osmo-logger\",}) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"default\", pod=~\"osmo-logger(.*)\", container=\"osmo-logger\", image!=\"\"}) by (pod))",
     "legendFormat": "Average"
    },
    {
     "expr": "avg(sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"default\", resource=\"memory\", pod=~\"osmo-logger(.*)\",container=\"osmo-logger\"}) by (pod))",
     "legendFormat": "Limits"
    },
    {
     "expr": "quantile(0.90, sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"default\", pod=~\"osmo-logger(.*)\", container=\"osmo-logger\", image!=\"\"}) by (pod))",
     "legendFormat": "Quantile90"
    }
   ]
  },
  { "title": "Router", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Router - CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum by (pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"default\", pod=~\"osmo-router(.*)\", container=\"osmo-router\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(sum by (pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"default\", pod=~\"osmo-router(.*)\", container=\"osmo-router\"}))",
     "legendFormat": "Average"
    },
    {
     "expr": "avg(sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"default\", resource=\"cpu\", pod=~\"osmo-router(.*)\", container=\"osmo-router\"})by (pod))",
     "legendFormat": "Requests"
    },
    {
     "expr": "quantile(0.90, sum by (pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"default\", pod=~\"osmo-router(.*)\", container=\"osmo-router\"}))",
     "legendFormat": "Quantile90"
    }
   ]
  },
  {
   "title": "Router - Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", namespace=\"default\", pod=~\"osmo-router(.*)\", container=\"osmo-router\",}) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"default\", pod=~\"osmo-router(.*)\", container=\"osmo-router\", image!=\"\"}) by (pod))",
     "legendFormat": "Average"
    },
    {
     "expr": "avg(sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"default\", resource=\"memory\", pod=~\"osmo-router(.*)\",container=\"osmo-router\"}) by (pod))",
     "legendFormat": "Limits"
    },
    {
     "expr": "quantile(0.90, sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"default\", pod=~\"osmo-router(.*)\", container=\"osmo-router\", image!=\"\"}) by (pod))",
     "legendFormat": "Quantile90"
    }
   ]
  },
  {
   "title": "Router - Autoscaler",
   "type": "timeseries",
   "description": "Number of running router instances",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "count(envoy_cluster_upstream_cx_active{envoy_cluster_name=\"service\", pod=~\"osmo-router-.*\"})",
     "legendFormat": "Number of Router Pods"
    },
    { "expr": "count(kube_node_info)", "legendFormat": "Number of Nodes" }
   ]
  },
  {
   "title": "Router - Active Connections",
   "type": "timeseries",
   "description": "That total number of ongoing port-forward/exec connections",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "envoy_cluster_upstream_cx_active{pod=~\"osmo-router.*\", envoy_cluster_name=\"service\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{pod=~\"osmo-router.*\", envoy_cluster_name=\"service\"})",
     "legendFormat": "Total connections"
    }
   ]
  },
  { "title": "Agent", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Agent - CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum by (pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"default\", pod=~\"osmo-agent(.*)\", container=\"osmo-agent\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(sum by (pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"default\", pod=~\"osmo-agent(.*)\", container=\"osmo-agent\"}))",
     "legendFormat": "Average"
    },
    {
     "expr": "avg(sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"default\", resource=\"cpu\", pod=~\"osmo-agent(.*)\",container=\"osmo-agent\"})by (pod))",
     "legendFormat": "Requests"
    },
    {
     "expr": "quantile(0.90, sum by (pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"default\", pod=~\"osmo-agent(.*)\", container=\"osmo-agent\"}))",
     "legendFormat": "Quantile90"
    }
   ]
  },
  {
   "title": "Agent - Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"default\", pod=~\"osmo-agent(.*)\", container=\"osmo-agent\"}) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"default\", pod=~\"osmo-agent(.*)\", container=\"osmo-agent\"}) by (pod))",
     "legendFormat": "Average"
    },
    {
     "expr": "avg(sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"default\", resource=\"memory\", pod=~\"osmo-agent(.*)\", container=\"osmo-agent\"}) by (pod))",
     "legendFormat": "Limits"
    },
    {
     "expr": "quantile(0.90, sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"default\", pod=~\"osmo-agent(.*)\", container=\"osmo-agent\"}) by (pod))",
     "legendFormat": "Quantile90"
    }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Job Queue",
   "type": "timeseries",
   "description": "Redis Queue for Jobs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "max by(job_type) (osmo_service_worker_job_queue_length{})",
     "legendFormat": "{{job_type}}"
    }
   ]
  },
  {
   "title": "Agent Queue",
   "type": "timeseries",
   "description": "Redis queue for K8s commands",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "max by(job_type) (osmo_backend_worker_job_queue_length)",
     "legendFormat": "{{job_type}}"
    }
   ]
  },
  { "title": "Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Worker - CPU",
   "type": "timeseries",
   "description": "Service Worker CPU",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "sum by (pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"default\", pod=~\"osmo-worker(.*)\", container=\"osmo-worker\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "Avg(sum by (pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"default\", pod=~\"osmo-worker(.*)\", container=\"osmo-worker\"}))",
     "legendFormat": "Average"
    },
    {
     "expr": "avg(sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"default\", resource=\"cpu\", pod=~\"osmo-worker(.*)\", container=\"osmo-worker\"}) by (pod))",
     "legendFormat": "Requests"
    },
    {
     "expr": "quantile(0.90, sum by (pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"default\", pod=~\"osmo-worker(.*)\", container=\"osmo-worker\"}))",
     "legendFormat": "Quantile90"
    }
   ]
  },
  {
   "title": "Worker - Memory",
   "type": "timeseries",
   "description": "Service Worker Memory",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", namespace=\"default\", pod=~\"osmo-worker(.*)\", container=\"osmo-worker\"}) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(sum(container_memory_working_set_bytes{job=\"kubelet\", namespace=\"default\", pod=~\"osmo-worker(.*)\", container=\"osmo-worker\"}) by (pod))",
     "legendFormat": "Average"
    },
    {
     "expr": "avg(sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"default\", resource=\"memory\", pod=~\"osmo-worker(.*)\", container=\"osmo-worker\"}) by(pod))",
     "legendFormat": "Limits"
    },
    {
     "expr": "quantile(0.9, sum(container_memory_working_set_bytes{job=\"kubelet\", namespace=\"default\", pod=~\"osmo-worker(.*)\", container=\"osmo-worker\"}) by (pod))",
     "legendFormat": "Quantile90"
    }
   ]
  },
  {
   "title": "Worker - Job Count / min",
   "type": "timeseries",
   "description": "Number of jobs per status",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "sum by (job_status, job_type) (increase(osmo_worker_job_processing_time_count{job_type!=\"CheckQueueTimeout\", job_type!=\"CheckRunTimeout\"}[1m:]))",
     "legendFormat": "{{job_type}}-{{job_status}}"
    },
    {
     "expr": "avg (sum by (job_status, job_type) (increase(osmo_worker_job_processing_time_count{job_type!=\"CheckQueueTimeout\", job_type!=\"CheckRunTimeout\"}[1m:])))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Worker - Job Latency",
   "type": "timeseries",
   "description": "Processing duration of Jobs by status",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, job_type, job_status) (rate(osmo_worker_job_processing_time_bucket{job_type!=\"CheckQueueTimeout\", job_type!=\"CheckRunTimeout\"}[5m:])))",
     "legendFormat": "{{job_type}}-{{job_status}}"
    },
    {
     "expr": "avg(histogram_quantile(0.95, sum by(le, job_type, job_status) (rate(osmo_worker_job_processing_time_bucket{job_type!=\"CheckQueueTimeout\", job_type!=\"CheckRunTimeout\"}[5m:]))))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Worker - Autoscaler",
   "type": "timeseries",
   "description": "Number of running worker instances",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "count(kube_pod_info{pod=~\"osmo-worker-.*\"})",
     "legendFormat": "Number of workers"
    },
    { "expr": "count(kube_node_info)", "legendFormat": "Number of Nodes" }
   ]
  },
  { "title": "Job Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Job Monitor - CPU",
   "type": "timeseries",
   "description": "Delayed Job Monitor CPU usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "sum by (pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"default\", pod=~\"osmo-delayed-job-monitor(.*)\", container=\"osmo-delayed-job-monitor\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(sum by (pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"default\", pod=~\"osmo-delayed-job-monitor(.*)\", container=\"osmo-delayed-job-monitor\"}))",
     "legendFormat": "Average"
    },
    {
     "expr": "avg(sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"default\", resource=\"cpu\", pod=~\"osmo-delayed-job-monitor(.*)\"}) by (pod))",
     "legendFormat": "Limits"
    },
    {
     "expr": "quantile(0.90, sum by (pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"default\", pod=~\"osmo-delayed-job-monitor(.*)\", container=\"osmo-delayed-job-monitor\"}))",
     "legendFormat": "Quantile90"
    }
   ]
  },
  {
   "title": "Job Monitor - Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"default\", pod=~\"osmo-delayed-job-monitor(.*)\" ,container=\"osmo-delayed-job-monitor\"}) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"default\", pod=~\"osmo-delayed-job-monitor(.*)\" ,container=\"osmo-delayed-job-monitor\"}) by (pod))",
     "legendFormat": "Average"
    },
    {
     "expr": "avg(sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"default\", resource=\"memory\", pod=~\"osmo-delayed-job-monitor(.*)\", container=\"osmo-delayed-job-monitor\"}) by (pod))",
     "legendFormat": "Limits"
    },
    {
     "expr": "quantile(0.90, sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"default\", pod=~\"osmo-delayed-job-monitor(.*)\" ,container=\"osmo-delayed-job-monitor\"}) by (pod))",
     "legendFormat": "Quantile90"
    }
   ]
  }
 ]
}