{
 "title": "Workflow Resources",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_configmap_info,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\"},namespace)"
    }
   },
   {
    "name": "uuid",
    "label": "uuid",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\", namespace=\"$namespace\"},pod)"
    }
   },
   {
    "name": "task_name",
    "label": "task",
    "query": {
     "query": "label_values(kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", container!=\"osmo-ctrl\"},container)"
    }
   },
   {
    "name": "Node",
    "label": "node",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\", pod=~\"$uuid.*\", cluster=\"$cluster\"},node)"
    }
   },
   { "name": "smoothing_interval", "label": "smoothing_interval", "query": "30s,1m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod, container) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$namespace\", pod=~'$uuid(.*)', container=~\"$task_name\"})",
     "legendFormat": "{{pod}}:{{container}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$uuid(.*)\", resource=\"cpu\", container=~\"$task_name\"}",
     "legendFormat": "{{pod}}:{{container}} - limits"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod, container) (container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$uuid(.*)\", node=~\"$Node\", container=~\"$task_name\"})",
     "legendFormat": "{{pod}}:{{container}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$uuid(.*)\", cluster=\"$cluster\", resource=\"memory\", container=~\"$task_name\"}",
     "legendFormat": "{{pod}}:{{container}} - limits"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{container=~\"$task_name\", pod=~\"$uuid(.*)\", resource=\"ephemeral_storage\", namespace=\"$namespace\", cluster=\"$cluster\"}",
     "legendFormat": "{{pod}}:{{container}} - limits"
    },
    {
     "expr": "ephemeral_storage_pod_usage{pod_namespace=\"$namespace\", cluster=\"$cluster\", pod_name=~\"$uuid(.*)\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(DCGM_FI_DEV_GPU_UTIL{exported_pod=~\"$uuid(.*)\", exported_namespace=\"$namespace\", cluster=\"$cluster\", exported_container=~\"$task_name\"} [$smoothing_interval])",
     "legendFormat": "{{exported_pod}}:{{exported_container}} - GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "avg_over_time(DCGM_FI_DEV_FB_USED{exported_pod=~\"$uuid(.*)\", exported_namespace=\"$namespace\", cluster=\"$cluster\",exported_container=~\"$task_name\"} [$smoothing_interval])",
     "legendFormat": "{{exported_pod}}:{{exported_container}} - GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Node Conditions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_node_status_condition{\n  cluster=\"$cluster\",\n  node=~\"${Node:pipe}\",\n  status=\"true\",\n  condition=~\"Gpu(.*)\"\n} == 1",
     "legendFormat": "{{node}}:{{condition}}"
    }
   ]
  },
  {
   "title": "GPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(DCGM_FI_PROF_GR_ENGINE_ACTIVE{exported_pod=~\"$uuid(.*)\", exported_namespace=\"$namespace\", cluster=\"$cluster\",exported_container=~\"$task_name\"} > .01 or DCGM_FI_PROF_DRAM_ACTIVE{exported_pod=~\"$uuid(.*)\", exported_namespace=\"$namespace\", cluster=\"$cluster\", exported_container=~\"$task_name\"} > 0.2) or vector(0)",
     "legendFormat": "Optmistic Usage"
    },
    {
     "expr": "count(DCGM_FI_PROF_GR_ENGINE_ACTIVE{exported_pod=~\"$uuid(.*)\", exported_namespace=\"$namespace\", cluster=\"$cluster\", exported_container=~\"$task_name\"} > -1) or vector(0)",
     "legendFormat": "Total GPU"
    }
   ]
  },
  {
   "title": "GPU Throttle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(floor(DCGM_FI_DEV_CLOCK_THROTTLE_REASONS{exported_namespace=\"$namespace\", cluster=\"$cluster\", exported_pod=~\"$uuid(.*)\", exported_container=~\"$task_name\"} / 1) % 2) == 1",
     "legendFormat": "{{exported_pod}}:{{exported_container}} - GPU {{gpu}}"
    }
   ]
  }
 ]
}