// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// The Operator Service is the central control-plane gateway. It accepts long-lived
// bidirectional gRPC streams from per-cluster TaskGroup Controllers. Through that one
// stream:
//
//   - Operator Service sends commands to the controller (CreateOTG, DeleteOTG,
//     ResyncRequest).
//   - Controller sends events back (status updates, command acks, heartbeats).
//
// Crucially: the controller is always the gRPC *client*. It initiates the outbound
// connection to the Operator Service. The Operator Service is never asked to dial into a
// cluster. This is what makes the design work for NAT'd / edge / private clusters.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.34.1
// source: operator.proto

package operatorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ClusterSession_Connect_FullMethodName = "/osmo.taskgroup.v1alpha1.ClusterSession/Connect"
)

// ClusterSessionClient is the client API for ClusterSession service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClusterSessionClient interface {
	// Connect is the long-lived bidirectional stream a controller opens at startup.
	// First message must be a Hello; subsequent messages carry status events and command
	// acknowledgements. The server pushes commands back over the same stream.
	Connect(ctx context.Context, opts ...grpc.CallOption) (ClusterSession_ConnectClient, error)
}

type clusterSessionClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterSessionClient(cc grpc.ClientConnInterface) ClusterSessionClient {
	return &clusterSessionClient{cc}
}

func (c *clusterSessionClient) Connect(ctx context.Context, opts ...grpc.CallOption) (ClusterSession_ConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &ClusterSession_ServiceDesc.Streams[0], ClusterSession_Connect_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &clusterSessionConnectClient{stream}
	return x, nil
}

type ClusterSession_ConnectClient interface {
	Send(*ControllerEnvelope) error
	Recv() (*OperatorEnvelope, error)
	grpc.ClientStream
}

type clusterSessionConnectClient struct {
	grpc.ClientStream
}

func (x *clusterSessionConnectClient) Send(m *ControllerEnvelope) error {
	return x.ClientStream.SendMsg(m)
}

func (x *clusterSessionConnectClient) Recv() (*OperatorEnvelope, error) {
	m := new(OperatorEnvelope)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ClusterSessionServer is the server API for ClusterSession service.
// All implementations must embed UnimplementedClusterSessionServer
// for forward compatibility
type ClusterSessionServer interface {
	// Connect is the long-lived bidirectional stream a controller opens at startup.
	// First message must be a Hello; subsequent messages carry status events and command
	// acknowledgements. The server pushes commands back over the same stream.
	Connect(ClusterSession_ConnectServer) error
	mustEmbedUnimplementedClusterSessionServer()
}

// UnimplementedClusterSessionServer must be embedded to have forward compatible implementations.
type UnimplementedClusterSessionServer struct {
}

func (UnimplementedClusterSessionServer) Connect(ClusterSession_ConnectServer) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedClusterSessionServer) mustEmbedUnimplementedClusterSessionServer() {}

// UnsafeClusterSessionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterSessionServer will
// result in compilation errors.
type UnsafeClusterSessionServer interface {
	mustEmbedUnimplementedClusterSessionServer()
}

func RegisterClusterSessionServer(s grpc.ServiceRegistrar, srv ClusterSessionServer) {
	s.RegisterService(&ClusterSession_ServiceDesc, srv)
}

func _ClusterSession_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClusterSessionServer).Connect(&clusterSessionConnectServer{stream})
}

type ClusterSession_ConnectServer interface {
	Send(*OperatorEnvelope) error
	Recv() (*ControllerEnvelope, error)
	grpc.ServerStream
}

type clusterSessionConnectServer struct {
	grpc.ServerStream
}

func (x *clusterSessionConnectServer) Send(m *OperatorEnvelope) error {
	return x.ServerStream.SendMsg(m)
}

func (x *clusterSessionConnectServer) Recv() (*ControllerEnvelope, error) {
	m := new(ControllerEnvelope)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ClusterSession_ServiceDesc is the grpc.ServiceDesc for ClusterSession service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClusterSession_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "osmo.taskgroup.v1alpha1.ClusterSession",
	HandlerType: (*ClusterSessionServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _ClusterSession_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "operator.proto",
}
