#!/usr/bin/env python3
"""
SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.  # pylint: disable=line-too-long

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

SPDX-License-Identifier: Apache-2.0

Export OSMO configs from a running instance to Helm values YAML format.

This script connects to an OSMO instance via its API and exports all
configuration into the format expected by the Helm chart's
services.configs section. Users can paste the output into their
Helm values file to migrate from DB-based to ConfigMap-based config.

The output is a minimal diff from the chart's built-in defaults — fields
whose values are identical to what the chart ships out-of-the-box are
stripped. Use --no-strip-defaults to get a full dump.

Usage:
    export OSMO_URL=https://osmo.example.com
    export OSMO_TOKEN=<access-token>
    python3 export_configs_to_helm.py > my-configs.yaml

    # Or with osmo CLI auth:
    python3 export_configs_to_helm.py --url https://osmo.example.com

Environment variables:
    OSMO_URL      Base URL of the OSMO service (required)
    OSMO_TOKEN    Access token for authentication (optional if using
                  --header for custom auth)
"""

import argparse
import json
import os
import pathlib
import sys
import urllib.error
import urllib.parse
import urllib.request

import yaml


# Minimum all-asterisk run length to treat as a server-side redaction mark.
# The service currently emits exactly `'**********'` (10 asterisks), but a
# length-based check is more forgiving if the mask ever changes.
MASKED_MIN_ASTERISKS = 8

# Placeholder emitted in the output wherever the exporter found a masked value.
# The operator replaces this with a real K8s Secret name.
TODO_PLACEHOLDER = 'TODO-REPLACE-ME'

# Runtime-generated fields that should NOT be in the ConfigMap.
# These are auto-generated by configure_app() on startup.
SERVICE_RUNTIME_FIELDS = {
    'service_auth',
    'service_base_url',
}

# Runtime fields on backends written by the agent, not by config.
BACKEND_RUNTIME_FIELDS = {
    'k8s_uid',
    'k8s_namespace',
    'version',
    'last_heartbeat',
    'created_date',
    'online',
}

# Computed fields on pools that are derived, not configured.
POOL_COMPUTED_FIELDS = {
    'status',
    'last_heartbeat',
    'parsed_resource_validations',
    'parsed_pod_template',
    'parsed_group_templates',
}

# Computed fields on platforms within pools. These are resolved at runtime
# from template/validation name references (override_pod_template,
# resource_validations, common_pod_template, common_resource_validations).
PLATFORM_COMPUTED_FIELDS = {
    'parsed_resource_validations',
    'parsed_pod_template',
    'parsed_group_templates',
    'tolerations',
    'labels',
    'default_mounts',
}

# Fields on roles that are internal metadata, not config.
ROLE_INTERNAL_FIELDS = {
    'sync_mode',
}

# Endpoints that may legitimately 400 when their DB table hasn't been created
# yet on the current schema version (e.g. group_template on pre-6.3 DBs).
# The script logs a short note and continues instead of dumping the full
# DATABASE error body.
OPTIONAL_CONFIG_ENDPOINTS = {
    'group_template',
}


def fetch(base_url, path, headers, optional=False):
    """Fetch JSON from the OSMO API.

    When optional=True and the API responds with HTTP 400 "relation … does
    not exist" (table absent on this schema version), logs a short message
    and returns None quietly instead of dumping the raw SQL error.
    """
    url = f'{base_url}{path}'
    parsed = urllib.parse.urlsplit(url)
    if parsed.scheme not in ('http', 'https'):
        print(f'Error: URL must use http or https scheme: {url}',
              file=sys.stderr)
        return None
    req = urllib.request.Request(url, headers=headers)
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return json.loads(resp.read())
    except urllib.error.HTTPError as error:
        body = ''
        try:
            body = error.read().decode()
        except Exception:  # pylint: disable=broad-except
            pass
        if (optional and error.code == 400
                and 'does not exist' in body
                and '"DATABASE"' in body):
            print(f'  (skipped {path}: table not present on this schema)',
                  file=sys.stderr)
            return None
        print(f'Error fetching {path}: HTTP {error.code}', file=sys.stderr)
        if body:
            print(f'  {body[:200]}', file=sys.stderr)
        return None
    except urllib.error.URLError as error:
        print(f'Error connecting to {url}: {error.reason}', file=sys.stderr)
        return None


def strip_fields(data, fields):
    """Remove specified keys from a dict."""
    if not isinstance(data, dict):
        return data
    return {k: v for k, v in data.items() if k not in fields}


def export_singleton(base_url, headers, config_type, strip):
    """Export a singleton config (service, workflow, dataset)."""
    data = fetch(base_url, f'/api/configs/{config_type}', headers)
    if data is None:
        return None
    data = strip_fields(data, strip)
    # Remove _configmap_mode flag if present
    data.pop('_configmap_mode', None)
    return data


def export_backends(base_url, headers):
    """Export backends, stripping runtime fields."""
    data = fetch(base_url, '/api/configs/backend', headers)
    if data is None:
        return None

    backends_list = data.get('backends', data)
    if isinstance(backends_list, list):
        items = {}
        for backend in backends_list:
            name = backend.pop('name', None)
            if name:
                items[name] = strip_fields(backend, BACKEND_RUNTIME_FIELDS)
        return items
    return None


def strip_platform_computed_fields(pool):
    """Strip computed fields from each platform within a pool."""
    platforms = pool.get('platforms')
    if not isinstance(platforms, dict):
        return
    for platform_data in platforms.values():
        if isinstance(platform_data, dict):
            for field in PLATFORM_COMPUTED_FIELDS:
                platform_data.pop(field, None)


def export_pools(base_url, headers):
    """Export pools in editable format, stripping computed fields."""
    data = fetch(base_url, '/api/configs/pool?verbose=true', headers)
    if data is None:
        return None

    pools_data = data.get('pools', data)
    if isinstance(pools_data, dict):
        items = {}
        for name, pool in pools_data.items():
            if isinstance(pool, dict):
                clean = strip_fields(pool, POOL_COMPUTED_FIELDS | {'name'})
                strip_platform_computed_fields(clean)
                items[name] = clean
            elif isinstance(pool, list):
                for pool_item in pool:
                    pool_name = pool_item.pop('name', name)
                    clean = strip_fields(pool_item, POOL_COMPUTED_FIELDS)
                    strip_platform_computed_fields(clean)
                    items[pool_name] = clean
        return items
    return None


def export_named_configs(base_url, headers, path):
    """Export named configs (pod_templates, resource_validations, etc.)."""
    optional = path in OPTIONAL_CONFIG_ENDPOINTS
    data = fetch(base_url, f'/api/configs/{path}', headers, optional=optional)
    if data is None:
        return None
    return data


def export_roles(base_url, headers):
    """Export roles, stripping internal fields."""
    data = fetch(base_url, '/api/configs/role', headers)
    if data is None:
        return None

    items = {}
    for role in data:
        name = role.pop('name', None)
        if name:
            items[name] = strip_fields(role, ROLE_INTERNAL_FIELDS)
    return items


def drop_empty(obj):
    """Recursively drop None, empty dicts, and empty lists.

    A field set to None (Pydantic-optional default) or an empty container
    is equivalent to omitting the field — stripping keeps exported files
    as minimal overrides rather than full dumps. Applied symmetrically
    inside dicts and lists: an item that cleans down to None or `{}` / `[]`
    is removed from its parent.
    """
    if isinstance(obj, dict):
        cleaned = {}
        for key, value in obj.items():
            new_value = drop_empty(value)
            if _is_empty(new_value):
                continue
            cleaned[key] = new_value
        return cleaned
    if isinstance(obj, list):
        cleaned = []
        for item in obj:
            new_item = drop_empty(item)
            if _is_empty(new_item):
                continue
            cleaned.append(new_item)
        return cleaned
    return obj


def _is_empty(value):
    return value is None or (isinstance(value, (dict, list)) and not value)


def strip_backend_image_pins(configs):
    """Remove pinned image tags from workflow.backend_images.

    The `init` / `client` fields pin specific image tags at export time.
    Keeping them silently locks workflow pods to the version that was
    running when the export happened — easy to miss during an upgrade.
    Strip them so the service falls back to defaults derived from
    global.osmoImageTag.
    """
    workflow = configs.get('workflow')
    if not isinstance(workflow, dict):
        return []
    backend_images = workflow.get('backend_images')
    if not isinstance(backend_images, dict):
        return []
    removed = []
    for key in ('init', 'client'):
        if key in backend_images:
            pinned = backend_images.pop(key)
            removed.append(f'workflow.backend_images.{key}={pinned}')
    return removed


def _is_masked(value):
    """True when value is a server-side redaction sentinel (run of asterisks).

    Tolerates mask-length changes in the service — any string that's pure
    asterisks and at least MASKED_MIN_ASTERISKS long counts.
    """
    return (isinstance(value, str)
            and len(value) >= MASKED_MIN_ASTERISKS
            and set(value) == {'*'})


def rewrite_masked_secrets(obj, path='', collected=None):
    """Replace masked values with TODO secretName placeholders in-place.

    Rewrites each masked scalar as `{secretName: TODO_PLACEHOLDER,
    secretKey: <field>}` — the operator replaces the placeholder with a
    real K8s Secret name and wires it into services.configs.secretRefs.
    Plaintext siblings (endpoint, region, access_key_id, registry,
    username, …) are left untouched so the operator sees what the
    credential was pointing at.

    Returns the accumulated list of (dotted_path, field_name) tuples so
    the caller can print a stderr summary of every TODO that needs
    wiring up.
    """
    if collected is None:
        collected = []
    if isinstance(obj, dict):
        for key in list(obj.keys()):
            full_path = f'{path}.{key}' if path else key
            value = obj[key]
            if _is_masked(value):
                obj[key] = {'secretName': TODO_PLACEHOLDER, 'secretKey': key}
                collected.append((full_path, key))
            else:
                rewrite_masked_secrets(value, full_path, collected)
    elif isinstance(obj, list):
        for i in range(len(obj)):
            item_path = f'{path}[{i}]'
            if _is_masked(obj[i]):
                # Bare masked scalar in a list — no field name to use as
                # secretKey, so flag with the index so the stderr summary
                # points at the exact slot.
                obj[i] = {'secretName': TODO_PLACEHOLDER,
                          'secretKey': f'item_{i}'}
                collected.append((item_path, f'item_{i}'))
            else:
                rewrite_masked_secrets(obj[i], item_path, collected)
    return collected


def load_chart_defaults(values_path):
    """Load services.configs.* from the chart's values.yaml to use as baseline.

    Returns an empty dict if the file can't be read or parsed — caller
    treats that as "no defaults available, skip diffing."
    """
    try:
        with open(values_path, encoding='utf-8') as f:
            values = yaml.safe_load(f) or {}
    except (OSError, yaml.YAMLError) as error:
        print(f'Warning: could not load chart defaults from {values_path}: '
              f'{error}', file=sys.stderr)
        return {}

    configs = values.get('services', {}).get('configs', {})
    # Drop the enabled flag — we always set that explicitly in the output.
    configs = {k: v for k, v in configs.items() if k != 'enabled'}
    # Normalize: the same drop_empty pass we run on the export, so sides
    # aren't asymmetric in how they represent "absent" fields. drop_empty
    # already returns a new tree, so no copy needed.
    return drop_empty(configs)


def diff_against_defaults(exported, defaults):
    """Deep-diff: drop keys in `exported` that equal `defaults`.

    - Scalars and lists: if equal, drop.
    - Dicts: recurse; if the recursed dict is empty, drop the key.
    - Named-dict sections (podTemplates, resourceValidations, roles, backends,
      pools): an entry is dropped if deep-equal to the chart's corresponding
      entry; otherwise kept as-is (no partial diffing inside a single named
      entry, since policies/platforms are intentionally all-or-nothing).
    """
    if not isinstance(exported, dict) or not isinstance(defaults, dict):
        return exported
    result = {}
    for key, exp_value in exported.items():
        def_value = defaults.get(key)
        if def_value is None:
            result[key] = exp_value
            continue

        if _is_named_dict_section(key, exp_value, def_value):
            kept = {
                name: entry
                for name, entry in exp_value.items()
                if entry != def_value.get(name)
            }
            if kept:
                result[key] = kept
            continue

        if isinstance(exp_value, dict) and isinstance(def_value, dict):
            nested = diff_against_defaults(exp_value, def_value)
            if nested:
                result[key] = nested
            continue

        if exp_value != def_value:
            result[key] = exp_value
    return result


def _is_named_dict_section(key, exp_value, def_value):
    """Sections keyed by user-chosen names (podTemplates, roles, …).

    These are dict-of-dicts where each child represents a single named
    entity. We compare entries whole rather than diffing inside them.
    """
    named_sections = {
        'podTemplates', 'resourceValidations', 'roles', 'backends', 'pools',
        'backendTests', 'groupTemplates',
    }
    return (key in named_sections
            and isinstance(exp_value, dict)
            and isinstance(def_value, dict))


def collect_secret_names(configs):
    """Walk the config dict and collect all secretName references.

    Skips the TODO_PLACEHOLDER emitted by rewrite_masked_secrets so the
    summary only lists real secretNames the operator has set.
    """
    secrets = set()
    if not isinstance(configs, dict):
        return secrets
    for key, value in configs.items():
        if (key == 'secretName' and isinstance(value, str)
                and value != TODO_PLACEHOLDER):
            secrets.add(value)
        elif isinstance(value, dict):
            secrets.update(collect_secret_names(value))
        elif isinstance(value, list):
            for item in value:
                if isinstance(item, dict):
                    secrets.update(collect_secret_names(item))
    return secrets


def _default_chart_values_path():
    """Resolve the chart values.yaml that ships next to this script."""
    here = pathlib.Path(__file__).resolve().parent
    return str(here.parent / 'charts' / 'service' / 'values.yaml')


def main():
    parser = argparse.ArgumentParser(
        description='Export OSMO configs to Helm values YAML format.',
        epilog='Output can be pasted into services.configs in your Helm values.',
    )
    parser.add_argument(
        '--url', default=os.environ.get('OSMO_URL', ''),
        help='OSMO service base URL (or set OSMO_URL env var)')
    parser.add_argument(
        '--token', default=os.environ.get('OSMO_TOKEN', ''),
        help='Access token (or set OSMO_TOKEN env var)')
    parser.add_argument(
        '--header', action='append', default=[],
        help='Custom header (e.g., "x-osmo-user: admin"). Can be repeated.')
    parser.add_argument(
        '--chart-values', default=_default_chart_values_path(),
        help='Path to chart values.yaml used as the "default" baseline for '
             'diffing. Defaults to ../charts/service/values.yaml relative '
             'to this script.')
    parser.add_argument(
        '--no-strip-defaults', action='store_true',
        help='Emit the full config tree instead of stripping fields that '
             'match the chart defaults.')
    args = parser.parse_args()

    if not args.url:
        parser.error('OSMO_URL or --url is required')

    base_url = args.url.rstrip('/')
    headers = {}
    if args.token:
        headers['Authorization'] = f'Bearer {args.token}'
    for header in args.header:
        key, _, value = header.partition(':')
        headers[key.strip()] = value.strip()

    print(f'# Exported from {base_url}', file=sys.stderr)
    print('# Paste this into services.configs in your Helm values.\n',
          file=sys.stderr)

    configs = {}

    # Singleton configs
    print('Exporting service config...', file=sys.stderr)
    service = export_singleton(
        base_url, headers, 'service', SERVICE_RUNTIME_FIELDS)
    if service:
        configs['service'] = service

    print('Exporting workflow config...', file=sys.stderr)
    workflow = export_singleton(base_url, headers, 'workflow', set())
    if workflow:
        configs['workflow'] = workflow

    print('Exporting dataset config...', file=sys.stderr)
    dataset = export_singleton(base_url, headers, 'dataset', set())
    if dataset:
        configs['dataset'] = dataset

    # Named configs
    print('Exporting backends...', file=sys.stderr)
    backends = export_backends(base_url, headers)
    if backends:
        configs['backends'] = backends

    print('Exporting pools...', file=sys.stderr)
    pools = export_pools(base_url, headers)
    if pools:
        configs['pools'] = pools

    # Named configs use camelCase keys to match Helm values convention.
    # The Helm chart template (configs.yaml) converts these to snake_case
    # when rendering the ConfigMap file that the loader reads.
    print('Exporting pod templates...', file=sys.stderr)
    pod_templates = export_named_configs(
        base_url, headers, 'pod_template')
    if pod_templates:
        configs['podTemplates'] = pod_templates

    print('Exporting resource validations...', file=sys.stderr)
    resource_validations = export_named_configs(
        base_url, headers, 'resource_validation')
    if resource_validations:
        configs['resourceValidations'] = resource_validations

    print('Exporting group templates...', file=sys.stderr)
    group_templates = export_named_configs(
        base_url, headers, 'group_template')
    if group_templates:
        configs['groupTemplates'] = group_templates

    print('Exporting backend tests...', file=sys.stderr)
    backend_tests = export_named_configs(
        base_url, headers, 'backend_test')
    if backend_tests:
        configs['backendTests'] = backend_tests

    print('Exporting roles...', file=sys.stderr)
    role_items = export_roles(base_url, headers)
    if role_items:
        configs['roles'] = role_items

    # 1. Drop None / empty-container keys (Pydantic defaults clutter).
    configs = drop_empty(configs)

    # 2. Strip pinned backend image tags — they silently lock workflow pods
    # to whatever version was running at export time.
    stripped_image_pins = strip_backend_image_pins(configs)

    # 3. Diff against the chart's shipped defaults. Only fields that differ
    # from the chart's out-of-the-box configs remain.
    defaults_used = False
    if not args.no_strip_defaults:
        defaults = load_chart_defaults(args.chart_values)
        if defaults:
            configs = diff_against_defaults(configs, defaults)
            defaults_used = True

    # 4. Rewrite masked secrets into secretName placeholders the operator
    # can fill in, and collect a summary of what they need to create.
    masked_fields = rewrite_masked_secrets(configs)

    # Collect secret references for secretRefs
    all_secrets = collect_secret_names(configs)
    secret_refs = [{'secretName': name} for name in sorted(all_secrets)]

    # Build final output
    output = {
        'services': {
            'configs': {
                'enabled': True,
                **({'secretRefs': secret_refs} if secret_refs else {}),
                **configs,
            },
        },
    }

    yaml.dump(output, sys.stdout, default_flow_style=False, sort_keys=False)

    # Operator guidance on stderr
    print(f'\nExported {len(configs)} config sections.', file=sys.stderr)
    if defaults_used:
        print('(Fields matching chart defaults were stripped. '
              'Pass --no-strip-defaults for the full tree.)',
              file=sys.stderr)
    if stripped_image_pins:
        print('\nStripped pinned backend image tags:', file=sys.stderr)
        for entry in stripped_image_pins:
            print(f'  - {entry}', file=sys.stderr)
        print('  (Falls back to global.osmoImageTag. Re-add under '
              'services.configs.workflow.backend_images if you want '
              'to pin explicitly.)', file=sys.stderr)
    if masked_fields:
        print('\nReplaced masked secret values with TODO placeholders at:',
              file=sys.stderr)
        for dotted_path, _ in masked_fields:
            print(f'  - services.configs.{dotted_path}', file=sys.stderr)
        print(f'  Create a K8s Secret for each and replace {TODO_PLACEHOLDER} '
              'with the real secretName. Add every secretName to '
              'services.configs.secretRefs so the chart mounts it.',
              file=sys.stderr)
    if secret_refs:
        print(f'\nFound {len(secret_refs)} existing secret references: '
              f'{[s["secretName"] for s in secret_refs]}', file=sys.stderr)
        print('Ensure these K8s Secrets exist in your namespace.',
              file=sys.stderr)


if __name__ == '__main__':
    main()
