# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.  # pylint: disable=line-too-long
# SPDX-License-Identifier: Apache-2.0
"""Create a PR from test files generated by Claude Code.

Detects new/modified test files, creates a branch, commits, pushes,
and opens a PR with the ai-generated label. Skips if no changes or
an unapproved ai-generated PR is already open.

Usage:
    python create_pr.py
    python create_pr.py --dry-run
"""

import argparse
from collections import Counter
import datetime
import json
import logging
import os
import re
import subprocess
import sys
from pathlib import Path
import urllib.error
import urllib.request
from typing import Any

from src.scripts.testbot.guardrails import get_changed_test_files

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(name)s] %(levelname)s: %(message)s",
)
logger = logging.getLogger(__name__)

SLACK_API_URL = "https://slack.com/api/chat.postMessage"
TESTBOT_SLACK_CHANNEL_DEFAULT = "#osmo-slack-test"
_SLACK_CHANNEL_IDS = {
    "#osmo-slack-test": "C0A8RJ738KZ",
}


def run(cmd: list[str], check: bool = True) -> subprocess.CompletedProcess:
    """Run a command, log failures, and return the result."""
    result = subprocess.run(cmd, capture_output=True, text=True, check=False)
    if result.returncode != 0:
        logger.error(
            "Command %s failed (exit %d):\nstdout: %s\nstderr: %s",
            cmd, result.returncode, result.stdout[:2000], result.stderr[:2000],
        )
        if check:
            result.check_returncode()
    return result


def has_unapproved_testbot_pr() -> bool:
    """Check if there is already an open unapproved testbot PR.

    Filters by both label and author so that developer PRs manually
    labeled ai-generated don't block new testbot runs.
    Returns True (fail closed) if the gh command fails.

    Bypass: when ``FORCE_CREATE_PR=true`` is exported in the
    environment, returns False unconditionally. This pairs with the
    workflow_dispatch ``force_create_pr`` input for end-to-end branch
    verification — without it, a real PR can't be generated while an
    unapproved testbot PR is already open, which is exactly the case
    when you're iterating on testbot itself.
    """
    if os.environ.get("FORCE_CREATE_PR", "").lower() == "true":
        logger.info(
            "FORCE_CREATE_PR=true; bypassing has_unapproved_testbot_pr",
        )
        return False
    result = run(
        ["gh", "pr", "list", "--label", "ai-generated", "--state", "open",
         "--author", "svc-osmo-ci",
         "--json", "number,reviewDecision",
         "--jq", '[.[] | select(.reviewDecision != "APPROVED")] | length'],
        check=False,
    )
    if result.returncode != 0:
        logger.error("gh pr list failed: %s", result.stderr[:200])
        return True
    try:
        return int(result.stdout.strip()) > 0
    except ValueError:
        return True


def _extract_pr_url(gh_output: str) -> str:
    """Extract a PR URL from gh output, tolerating extra log lines."""
    lines = [line.strip() for line in gh_output.splitlines() if line.strip()]
    for line in reversed(lines):
        if line.startswith(("http://", "https://")):
            return line
    return ""


def _enable_auto_merge(pr_url: str) -> bool:
    """Enable auto-merge for a created testbot PR."""
    if not pr_url:
        logger.error("PR URL is empty; cannot enable auto-merge")
        return False
    result = run(
        ["gh", "pr", "merge", "--auto", "--squash", pr_url],
        check=False,
    )
    if result.returncode != 0:
        logger.error("Failed to enable auto-merge for %s", pr_url)
        return False
    logger.info("Enabled auto-merge for %s", pr_url)
    return True


# Match SUSPECTED BUG markers Claude leaves on skipped tests. Accepts
# both forms the convention has produced in practice:
#   - canonical sibling comment:
#       # SUSPECTED BUG: foo.py:fn — desc
#       // SUSPECTED BUG: foo.go:Fn — desc
#   - the marker inlined as the skip-decorator reason string:
#       @unittest.skip('Suspected source bug: foo assumes X but receives Y')
#       t.Skip("Suspected library bug: ...")
# The second form is what surfaced on PR #1046 — Claude wrote the marker
# as the skip reason and never added the sibling comment, so the original
# strict regex missed it and the PR body's "Suspected bugs" section
# silently dropped a real signal. Stay anchored to a comment prefix or
# an opening quote so generic prose mentions ("# this is a suspected
# bug in the code") are still excluded.
_SUSPECTED_BUG_RE = re.compile(
    r"""(?xi)               # verbose, case-insensitive
    (?:\#|//|['\"])         # comment marker, or opening quote of a string literal
    \s*
    Suspected               # always starts with this word
    (?:\s+\w+)?             # optional adjective ("source", "library", ...)
    \s+
    bug                     # always ends with "bug"
    \s*:?\s*                # optional colon
    (.+)                    # the description; trailing quotes/parens
                            # are stripped in _scan_suspected_bugs
    """
)

# Best-effort fallback for ad-hoc runs without picker metadata. Normal
# workflow runs get their source targets directly from targets_meta.json;
# generated test names are output artifacts and do not reliably encode the
# source they exercise (for example, test_task_pure.py tests task.py).
_TEST_TO_SOURCE_PATTERNS: tuple[tuple[re.Pattern[str], str], ...] = (
    (re.compile(r"(.*?)/tests/test_([^/]+\.py)$"), r"\1/\2"),
    (re.compile(r"(.+)_test(\.go)$"), r"\1\2"),
    (re.compile(r"(.+)\.test(\.tsx?)$"), r"\1\2"),
)


def _test_to_source_paths(test_path: str) -> list[str]:
    """Return the source paths a test file may cover, most-specific first.

    Returns a list because a Go integration test name like
    ``foo_integration_test.go`` is ambiguous: it could test
    ``foo_integration.go`` (the naive ``_test`` strip) *or* ``foo.go``
    (the OSMO convention for integration tests of ``foo.go``, e.g.,
    ``user_role_sync_integration_test.go`` → ``user_role_sync.go``,
    ``authz_server_integration_test.go`` → ``authz_server.go``). PR
    #1058 surfaced this — the naive strip didn't match the picker's
    meta key and the rationale section got dropped.

    This is used only when picker metadata is unavailable. Callers prefer a
    candidate that exists on disk before falling back to the conventional
    first result.
    """
    candidates: list[str] = []
    for pattern, replacement in _TEST_TO_SOURCE_PATTERNS:
        match = pattern.fullmatch(test_path)
        if match:
            candidates.append(pattern.sub(replacement, test_path))
            break
    # Go integration test fallback: strip the trailing `_integration`
    # too. Added after the naive strip so callers prefer the more
    # specific match when both candidates exist in meta.
    if test_path.endswith("_integration_test.go"):
        base = test_path[: -len("_integration_test.go")]
        simplified = f"{base}.go"
        if simplified not in candidates:
            candidates.append(simplified)
    return candidates


def _test_to_source_path(test_path: str) -> str | None:
    """Return the most-specific source path a test file covers.

    Backward-compatible wrapper around :func:`_test_to_source_paths`
    for callers (and existing tests) that need a single value.
    """
    candidates = _test_to_source_paths(test_path)
    return candidates[0] if candidates else None


def _load_targets_meta(path: str) -> dict[str, dict]:
    """Read the picker sidecar JSON into a {source_path: meta} dict.

    Missing or malformed files yield an empty map so the PR-creation
    flow never blocks on a stale or absent meta file.
    """
    if not path:
        return {}
    try:
        entries = json.loads(Path(path).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        logger.warning("Could not read targets meta %s: %s", path, exc)
        return {}
    if not isinstance(entries, list):
        logger.warning("targets meta is not a list: %r", entries)
        return {}
    meta: dict[str, dict] = {}
    for entry in entries:
        if not isinstance(entry, dict):
            continue
        raw_file_path = entry.get("file_path")
        if not isinstance(raw_file_path, str) or not raw_file_path.strip():
            logger.warning(
                "Skipping target metadata entry with invalid file_path: %r",
                entry,
            )
            continue
        file_path = raw_file_path.strip()
        if file_path in meta:
            logger.warning(
                "Duplicate target metadata for %s; using the last entry",
                file_path,
            )
        meta[file_path] = entry
    return meta


def _source_paths_for_pr(
    changed_files: list[str],
    meta: dict[str, dict],
) -> list[str]:
    """Return source targets for the PR, preserving authoritative order.

    Picker metadata records what the workflow selected and is therefore the
    source of truth. Generated test paths only describe how the generator
    organized its output; one source can have multiple semantically named test
    files, and one test can exercise multiple selected sources.

    Filename inference remains as a compatibility fallback for local or ad-hoc
    runs that do not provide picker metadata.
    """
    if meta:
        return list(meta)

    logger.warning(
        "No target metadata available; inferring source paths from test names",
    )
    source_paths: list[str] = []
    seen: set[str] = set()
    for test_path in changed_files:
        candidates = _test_to_source_paths(test_path)
        if not candidates:
            continue
        source_path = next(
            (candidate for candidate in candidates if Path(candidate).is_file()),
            candidates[0],
        )
        if source_path not in seen:
            seen.add(source_path)
            source_paths.append(source_path)
    return source_paths


def _files_summary_for_pr(
    source_paths: list[str],
    changed_files: list[str],
) -> str:
    """Summarize source targets for titles and commit subjects.

    Unique source basenames stay compact. When multiple selected sources share
    a basename, their full paths disambiguate them. Changed-file basenames are
    used only when no source target can be resolved.
    """
    if not source_paths:
        changed_basenames = {
            path.rsplit("/", maxsplit=1)[-1] for path in changed_files
        }
        return ", ".join(sorted(changed_basenames))

    basenames = [path.rsplit("/", maxsplit=1)[-1] for path in source_paths]
    basename_counts = Counter(basenames)
    summary_parts = {
        path if basename_counts[basename] > 1 else basename
        for path, basename in zip(source_paths, basenames, strict=True)
    }
    return ", ".join(sorted(summary_parts))


def _build_generator_summary_section(path: str) -> str:
    """Render the generator's final summary into the PR body.

    The Generate step writes the LLM's final ``result`` text — which
    typically contains the LLM's own per-target coverage breakdown,
    per-range hit/miss reasoning, and a "Files changed" recap — to
    ``$RUNNER_TEMP/generate_summary.md``. Embedding that block in the
    PR body gives reviewers the same narrative the LLM produced
    instead of only the harness's bare-numbers coverage section.

    Missing / unreadable summary file yields an empty string so the PR
    opens unchanged. Leading/trailing whitespace is stripped to avoid
    extra blank lines around the section.
    """
    if not path:
        return ""
    try:
        body = Path(path).read_text(encoding="utf-8").strip()
    except OSError as exc:
        logger.warning("Could not read generator summary %s: %s", path, exc)
        return ""
    if not body:
        return ""
    return f"## Generator summary\n\n{body}\n"


def _build_coverage_section(path: str) -> str:
    """Render the coverage-gain section from verify_coverage.py's JSON.

    The verifier writes one entry per picker target with the listed-line
    hit count and per-range outcome. Missing / unreadable reports yield
    an empty string so the PR opens unchanged. Below-threshold files get
    a ⚠️ marker so reviewers can scan the gap at a glance — for example
    ``2/121 lines (2%)`` should jump out the way the roles.go PR did.
    """
    if not path:
        return ""
    try:
        reports = json.loads(Path(path).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        logger.warning("Could not read coverage report %s: %s", path, exc)
        return ""
    if not isinstance(reports, list) or not reports:
        return ""

    lines: list[str] = ["## Coverage gain on listed uncovered ranges", ""]
    for entry in reports:
        if not isinstance(entry, dict):
            continue
        file_path = entry.get("file_path", "")
        if not file_path:
            continue
        # Fail-soft on malformed values so a stray string in one field can't
        # abort PR creation — we'd rather show 0 and let the reviewer see the
        # gap than block the whole pipeline on a typo upstream.
        try:
            listed = int(entry.get("listed_lines", 0) or 0)
        except (TypeError, ValueError):
            listed = 0
        try:
            hit = int(entry.get("hit_lines", 0) or 0)
        except (TypeError, ValueError):
            hit = 0
        try:
            hit_fraction = float(entry.get("hit_fraction", 0.0) or 0.0)
        except (TypeError, ValueError):
            hit_fraction = 0.0
        passed = bool(entry.get("passed", False))
        lcov_seen = bool(entry.get("lcov_seen", True))
        if not lcov_seen:
            marker = "❔"
            note = (
                " — file not found in LCOV (test target may not have run; "
                "the harness ran `bazel coverage` over //... after generation)"
            )
        else:
            marker = "✅" if passed else "⚠️"
            note = ""
        lines.append(
            f"{marker} **`{file_path}`** — "
            f"{hit}/{listed} listed lines hit ({hit_fraction * 100:.0f}%)"
            f"{note}"
        )
        # Detail per range so reviewers can spot which specific blocks
        # the bot missed without leaving the PR view.
        for r in entry.get("ranges", []) or []:
            if not isinstance(r, dict):
                continue
            start = r.get("start")
            end = r.get("end")
            hit_lines = r.get("hit_lines", 0)
            total_lines = r.get("total_lines", 0)
            covered = bool(r.get("covered", False))
            if start is None or end is None:
                continue
            span = f"line {start}" if start == end else f"lines {start}-{end}"
            check = "✅" if covered else "❌"
            lines.append(
                f"  - {check} {span} — {hit_lines}/{total_lines} hit"
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _build_rationale_section(meta: dict[str, dict]) -> str:
    """Render the 'Why ... was targeted' section, or '' when no rationale."""
    if not meta:
        return ""
    heading = (
        "## Why this file was targeted"
        if len(meta) == 1
        else "## Why these files were targeted"
    )
    blocks: list[str] = [heading, ""]
    for source, entry in meta.items():
        try:
            coverage = float(entry.get("coverage_pct", 0.0))
        except (TypeError, ValueError):
            coverage = 0.0
        try:
            uncovered = int(entry.get("uncovered_lines", 0))
        except (TypeError, ValueError):
            uncovered = 0
        raw_reason = entry.get("reason")
        reason = raw_reason.strip() if isinstance(raw_reason, str) else ""
        blocks.append(
            f"**`{source}`** — {coverage:.1f}% coverage, "
            f"{uncovered} uncovered lines."
        )
        if reason:
            blocks.append("")
            blocks.extend(f"> {line}" for line in reason.splitlines())
        blocks.append("")
    return "\n".join(blocks).rstrip() + "\n"


def _scan_suspected_bugs(files: list[str]) -> list[str]:
    """Scan test files for SUSPECTED BUG markers left by Claude."""
    seen: set[str] = set()
    bugs: list[str] = []
    for filepath in files:
        try:
            with open(filepath, encoding="utf-8") as fh:
                for line in fh:
                    match = _SUSPECTED_BUG_RE.search(line)
                    if match:
                        # Strip trailing characters left over from
                        # string-literal markers: closing quote,
                        # closing paren, comma, backslash for line
                        # continuation, plus surrounding whitespace.
                        description = match.group(1).strip(" \t\r\n'\"),\\")
                        if description and description not in seen:
                            seen.add(description)
                            bugs.append(description)
        except OSError:
            logger.warning("Could not read %s for bug markers", filepath)
    return bugs


def _resolve_slack_channel(channel: str) -> str:
    """Resolve known Slack channel names to IDs; pass through direct IDs."""
    return _SLACK_CHANNEL_IDS.get(channel, channel)


def _get_slack_bot_token() -> str:
    """Return the configured Slack bot token, if any."""
    return os.environ.get("TESTBOT_SLACK_BOT_TOKEN") or ""


def _build_slack_review_text(pr_url: str, pr_title: str) -> str:
    """Build the brief review request text for Slack."""
    target = pr_title.removeprefix("[testbot] Add tests for ").strip()
    if target:
        return f"Please review {pr_url} to add test for {target}."
    return f"Please review {pr_url}."


def _build_slack_review_payload(
    channel: str,
    pr_url: str,
    pr_title: str,
) -> dict[str, Any]:
    """Build a brief Slack Block Kit payload asking reviewers to review."""
    message = _build_slack_review_text(pr_url, pr_title)

    return {
        "channel": _resolve_slack_channel(channel),
        "text": message,
        "blocks": [
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": message,
                },
            },
        ],
    }


def _post_slack_review_request(
    bot_token: str,
    channel: str,
    pr_url: str,
    pr_title: str,
) -> bool:
    """Post a fail-soft Slack review request after a PR is created."""
    if not bot_token:
        logger.warning(
            "TESTBOT_SLACK_BOT_TOKEN not set; skipping Slack review request",
        )
        return False
    if not channel:
        # Empty channel is an explicit opt-out (workflow_dispatch input
        # cleared by the operator). Log at info rather than warning so
        # ad-hoc runs don't generate noise.
        logger.info(
            "TESTBOT_SLACK_CHANNEL is empty; skipping Slack review request",
        )
        return False
    if not pr_url:
        logger.warning("PR URL is empty; skipping Slack review request")
        return False

    payload = _build_slack_review_payload(
        channel=channel,
        pr_url=pr_url,
        pr_title=pr_title,
    )
    request = urllib.request.Request(
        SLACK_API_URL,
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {bot_token}",
            "Content-Type": "application/json; charset=utf-8",
        },
        method="POST",
    )

    try:
        with urllib.request.urlopen(request, timeout=10) as response:
            response_body = response.read().decode("utf-8")
    except (TimeoutError, urllib.error.URLError) as exc:
        logger.warning("Slack review request failed: %s", exc)
        return False

    try:
        response_json = json.loads(response_body)
    except json.JSONDecodeError:
        logger.warning(
            "Slack review request returned invalid JSON: %s",
            response_body,
        )
        return False

    if response_json.get("ok") is not True:
        logger.warning(
            "Slack API error while posting review request: %s",
            response_json.get("error", "unknown"),
        )
        return False

    message_ts = str(response_json.get("ts", "unknown"))
    logger.info(
        "Slack review request posted to %s (ts=%s): %s",
        channel,
        message_ts,
        pr_url,
    )
    return True


def main() -> None:
    """Detect changes, create branch, commit, push, and open PR."""
    parser = argparse.ArgumentParser(
        description="Create a PR from AI-generated test files.",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Show what would be done without creating a PR",
    )
    parser.add_argument(
        "--targets-meta", default="",
        help="Optional path to the picker's JSON metadata; when provided, "
             "the PR body includes the 'Why this file was targeted' section",
    )
    parser.add_argument(
        "--coverage-report", default="",
        help="Optional path to verify_coverage.py's JSON report; when "
             "provided, the PR body includes a 'Coverage gain on listed "
             "uncovered ranges' section so reviewers can see how many of "
             "the picker's listed lines the generated tests actually hit",
    )
    parser.add_argument(
        "--generate-summary", default="",
        help="Optional path to the LLM's final result text dumped by the "
             "Generate step. When present, embedded verbatim in a "
             "'Generator summary' section so reviewers see the LLM's own "
             "narrative (per-target breakdown, still-uncovered reasoning, "
             "files changed) alongside the harness's bare-numbers report.",
    )
    args = parser.parse_args()

    if has_unapproved_testbot_pr():
        logger.info(
            "An unapproved ai-generated PR is already open. "
            "Skipping to avoid stacking review work.",
        )
        return

    changed_files = get_changed_test_files()
    if not changed_files:
        logger.info("No test files generated, nothing to commit.")
        return

    logger.info("Changed test files: %s", changed_files)

    # Picker metadata is authoritative for the selected source targets.
    # Generated test filenames describe output organization and may not
    # mirror source basenames (for example, test_task_pure.py tests task.py).
    targets_meta = _load_targets_meta(args.targets_meta)
    if args.targets_meta and not targets_meta:
        logger.error(
            "Target metadata was provided but contained no valid targets: %s",
            args.targets_meta,
        )
        sys.exit(1)
    source_paths = _source_paths_for_pr(changed_files, targets_meta)

    # Title names selected source files, not generated tests or BUILD wiring.
    files_summary = _files_summary_for_pr(source_paths, changed_files)

    # "Targets selected" lists the source files chosen by the picker. It does
    # not claim a one-to-one mapping to generated files; per-target coverage
    # below reports how much each selected source was actually exercised.
    # Fall back to changed files only for ad-hoc runs without metadata.
    if source_paths:
        files_list = "\n".join(f"- `{p}`" for p in source_paths)
    else:
        files_list = "\n".join(f"- `{f}`" for f in changed_files)

    branch = f"testbot/{datetime.datetime.now(tz=datetime.timezone.utc).strftime("%Y%m%d-%H%M")}"

    if args.dry_run:
        logger.info("Dry run — would create branch '%s' with files:\n%s", branch, files_list)
        return

    run(["git", "checkout", "-b", branch])
    run(["git", "add"] + changed_files)
    subprocess.run(
        ["git", "commit", "-m", f"Add AI-generated tests for {files_summary}"],
        check=True,
    )
    push_result = run(["git", "push", "-u", "origin", branch], check=False)
    if push_result.returncode != 0:
        logger.error("Failed to push branch '%s'", branch)
        sys.exit(1)
    logger.info("Pushed branch '%s'", branch)

    suspected_bugs = _scan_suspected_bugs(changed_files)
    bugs_section = ""
    if suspected_bugs:
        bugs_list = "\n".join(f"- {bug}" for bug in suspected_bugs)
        bugs_section = f"\n## Suspected bugs\n{bugs_list}\n"

    # targets_meta already loaded above for the title computation.
    rationale_section = _build_rationale_section(targets_meta)
    if rationale_section:
        rationale_section = "\n" + rationale_section

    coverage_section = _build_coverage_section(args.coverage_report)
    if coverage_section:
        coverage_section = "\n" + coverage_section

    generator_summary_section = _build_generator_summary_section(
        args.generate_summary,
    )
    if generator_summary_section:
        generator_summary_section = "\n" + generator_summary_section

    pr_title = f"[testbot] Add tests for {files_summary}"
    pr_body = f"""## Summary
AI-generated tests targeting file(s) with low coverage.

Issue - None

## Targets selected
{files_list}
{rationale_section}{generator_summary_section}{coverage_section}{bugs_section}
## Checklist
- [x] I am familiar with the Contributing Guidelines
- [x] New or existing tests cover these changes
- [x] The documentation is up to date with these changes

---
Generated by testbot pipeline"""

    result = subprocess.run(
        ["gh", "pr", "create",
         "--title", pr_title,
         "--label", "ai-generated",
         "--base", "main",
         "--body", pr_body],
        capture_output=True, text=True, check=False,
    )
    if result.returncode != 0:
        logger.error("Failed to create PR: %s", result.stderr)
        sys.exit(1)

    pr_url = _extract_pr_url(result.stdout)
    logger.info("PR created: %s", pr_url or result.stdout.strip())
    if not _enable_auto_merge(pr_url):
        sys.exit(1)
    # SKIP_SLACK is the workflow_dispatch opt-out signal. GHA
    # expressions treat empty string as falsy (`'' || X` collapses to
    # X), so we can't use a YAML expression to *blank* the channel/
    # token env vars — we use a separate string-typed env instead and
    # check it here. Same pattern as FORCE_CREATE_PR.
    if os.environ.get("SKIP_SLACK", "").lower() == "true":
        logger.info("SKIP_SLACK=true; skipping Slack review request")
    else:
        # Resolve channel with the unset-vs-empty distinction:
        #   - var absent (e.g., local debug)   → fall back to the default
        #   - var present and empty            → propagate "" so the
        #     downstream helper short-circuits
        raw_channel = os.environ.get("TESTBOT_SLACK_CHANNEL")
        channel = (
            TESTBOT_SLACK_CHANNEL_DEFAULT if raw_channel is None else raw_channel
        )
        _post_slack_review_request(
            bot_token=_get_slack_bot_token(),
            channel=channel,
            pr_url=pr_url,
            pr_title=pr_title,
        )


if __name__ == "__main__":
    main()
