# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.  # pylint: disable=line-too-long
# SPDX-License-Identifier: Apache-2.0
"""Create a PR from test files generated by Claude Code.

Detects new/modified test files, creates a branch, commits, pushes,
and opens a PR with the ai-generated label. Skips if no changes or
an ai-generated PR is already open.

Usage:
    python create_pr.py
    python create_pr.py --dry-run
"""

import argparse
import datetime
import json
import logging
import os
import re
import subprocess
import sys
import urllib.error
import urllib.request
from typing import Any

from src.scripts.testbot.guardrails import get_changed_test_files

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(name)s] %(levelname)s: %(message)s",
)
logger = logging.getLogger(__name__)

SLACK_API_URL = "https://slack.com/api/chat.postMessage"
TESTBOT_SLACK_CHANNEL_DEFAULT = "#osmo-slack-test"
_SLACK_CHANNEL_IDS = {
    "#osmo-slack-test": "C0A8RJ738KZ",
}


def run(cmd: list[str], check: bool = True) -> subprocess.CompletedProcess:
    """Run a command, log failures, and return the result."""
    result = subprocess.run(cmd, capture_output=True, text=True, check=False)
    if result.returncode != 0:
        logger.error(
            "Command %s failed (exit %d):\nstdout: %s\nstderr: %s",
            cmd, result.returncode, result.stdout[:2000], result.stderr[:2000],
        )
        if check:
            result.check_returncode()
    return result


def has_open_testbot_pr() -> bool:
    """Check if there is already an open testbot PR.

    Filters by both label and author so that developer PRs manually
    labeled ai-generated don't block new testbot runs.
    Returns True (fail closed) if the gh command fails.
    """
    result = run(
        ["gh", "pr", "list", "--label", "ai-generated", "--state", "open",
         "--author", "svc-osmo-ci",
         "--json", "number", "--jq", "length"],
        check=False,
    )
    if result.returncode != 0:
        logger.error("gh pr list failed: %s", result.stderr[:200])
        return True
    try:
        return int(result.stdout.strip()) > 0
    except ValueError:
        return True


_SUSPECTED_BUG_RE = re.compile(r"(?:#|//)\s*SUSPECTED BUG:\s*(.+)")


def _scan_suspected_bugs(files: list[str]) -> list[str]:
    """Scan test files for SUSPECTED BUG markers left by Claude."""
    seen: set[str] = set()
    bugs: list[str] = []
    for filepath in files:
        try:
            with open(filepath, encoding="utf-8") as fh:
                for line in fh:
                    match = _SUSPECTED_BUG_RE.search(line)
                    if match:
                        description = match.group(1).strip()
                        if description not in seen:
                            seen.add(description)
                            bugs.append(description)
        except OSError:
            logger.warning("Could not read %s for bug markers", filepath)
    return bugs


def _resolve_slack_channel(channel: str) -> str:
    """Resolve known Slack channel names to IDs; pass through direct IDs."""
    return _SLACK_CHANNEL_IDS.get(channel, channel)


def _get_slack_bot_token() -> str:
    """Return the configured Slack bot token, if any."""
    return (
        os.environ.get("TESTBOT_SLACK_BOT_TOKEN")
        or os.environ.get("SLACK_RELEASE_BOT_TOKEN")
        or ""
    )


def _extract_pr_url(gh_output: str) -> str:
    """Extract the PR URL from gh output, tolerating extra log lines."""
    lines = [line.strip() for line in gh_output.splitlines() if line.strip()]
    for line in reversed(lines):
        if line.startswith(("http://", "https://")):
            return line
    return lines[-1] if lines else ""


def _build_slack_review_text(pr_url: str, pr_title: str) -> str:
    """Build the brief review request text for Slack."""
    target = pr_title.removeprefix("[testbot] Add tests for ").strip()
    if target:
        return f"Please review {pr_url} to add test for {target}."
    return f"Please review {pr_url}."


def _build_slack_review_payload(
    channel: str,
    pr_url: str,
    pr_title: str,
) -> dict[str, Any]:
    """Build a brief Slack Block Kit payload asking reviewers to review."""
    message = _build_slack_review_text(pr_url, pr_title)

    return {
        "channel": _resolve_slack_channel(channel),
        "text": message,
        "blocks": [
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": message,
                },
            },
        ],
    }


def _post_slack_review_request(
    bot_token: str,
    channel: str,
    pr_url: str,
    pr_title: str,
) -> bool:
    """Post a fail-soft Slack review request after a PR is created."""
    if not bot_token:
        logger.warning(
            "TESTBOT_SLACK_BOT_TOKEN/SLACK_RELEASE_BOT_TOKEN not set; "
            "skipping Slack review request",
        )
        return False
    if not pr_url:
        logger.warning("PR URL is empty; skipping Slack review request")
        return False

    payload = _build_slack_review_payload(
        channel=channel,
        pr_url=pr_url,
        pr_title=pr_title,
    )
    request = urllib.request.Request(
        SLACK_API_URL,
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {bot_token}",
            "Content-Type": "application/json; charset=utf-8",
        },
        method="POST",
    )

    try:
        with urllib.request.urlopen(request, timeout=10) as response:
            response_body = response.read().decode("utf-8")
    except (TimeoutError, urllib.error.URLError) as exc:
        logger.warning("Slack review request failed: %s", exc)
        return False

    try:
        response_json = json.loads(response_body)
    except json.JSONDecodeError:
        logger.warning(
            "Slack review request returned invalid JSON: %s",
            response_body,
        )
        return False

    if response_json.get("ok") is not True:
        logger.warning(
            "Slack API error while posting review request: %s",
            response_json.get("error", "unknown"),
        )
        return False

    message_ts = str(response_json.get("ts", "unknown"))
    logger.info(
        "Slack review request posted to %s (ts=%s): %s",
        channel,
        message_ts,
        pr_url,
    )
    return True


def main() -> None:
    """Detect changes, create branch, commit, push, and open PR."""
    parser = argparse.ArgumentParser(
        description="Create a PR from AI-generated test files.",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Show what would be done without creating a PR",
    )
    args = parser.parse_args()

    if has_open_testbot_pr():
        logger.info("An ai-generated PR is already open. Skipping to avoid stacking.")
        return

    changed_files = get_changed_test_files()
    if not changed_files:
        logger.info("No test files generated, nothing to commit.")
        return

    logger.info("Changed test files: %s", changed_files)

    basenames = sorted({f.rsplit("/", maxsplit=1)[-1] for f in changed_files})
    # Strip test prefixes/suffixes to show source file names in the PR title.
    # test_foo.py → foo.py, foo_test.go → foo.go, foo.test.ts → foo.ts
    source_names = sorted({
        re.sub(r"^test_", "", re.sub(r"[._]test(\.\w+)$", r"\1", name))
        for name in basenames
    })
    files_summary = ", ".join(source_names)
    files_list = "\n".join(f"- `{f}`" for f in changed_files)

    branch = f"testbot/{datetime.datetime.now(tz=datetime.timezone.utc).strftime("%Y%m%d-%H%M")}"

    if args.dry_run:
        logger.info("Dry run — would create branch '%s' with files:\n%s", branch, files_list)
        return

    run(["git", "checkout", "-b", branch])
    run(["git", "add"] + changed_files)
    subprocess.run(
        ["git", "commit", "-m", f"Add AI-generated tests for {files_summary}"],
        check=True,
    )
    push_result = run(["git", "push", "-u", "origin", branch], check=False)
    if push_result.returncode != 0:
        logger.error("Failed to push branch '%s'", branch)
        sys.exit(1)
    logger.info("Pushed branch '%s'", branch)

    suspected_bugs = _scan_suspected_bugs(changed_files)
    bugs_section = ""
    if suspected_bugs:
        bugs_list = "\n".join(f"- {bug}" for bug in suspected_bugs)
        bugs_section = f"\n## Suspected bugs\n{bugs_list}\n"

    pr_title = f"[testbot] Add tests for {files_summary}"
    pr_body = f"""## Summary
AI-generated tests targeting file(s) with low coverage.

Issue - None

## Files tested
{files_list}
{bugs_section}
## Checklist
- [x] I am familiar with the Contributing Guidelines
- [x] New or existing tests cover these changes
- [x] The documentation is up to date with these changes

---
Generated by testbot pipeline"""

    result = subprocess.run(
        ["gh", "pr", "create",
         "--title", pr_title,
         "--label", "ai-generated",
         "--base", "main",
         "--body", pr_body],
        capture_output=True, text=True, check=False,
    )
    if result.returncode != 0:
        logger.error("Failed to create PR: %s", result.stderr)
        sys.exit(1)

    pr_url = _extract_pr_url(result.stdout)
    logger.info("PR created: %s", pr_url)
    _post_slack_review_request(
        bot_token=_get_slack_bot_token(),
        channel=os.environ.get("TESTBOT_SLACK_CHANNEL")
        or TESTBOT_SLACK_CHANNEL_DEFAULT,
        pr_url=pr_url,
        pr_title=pr_title,
    )


if __name__ == "__main__":
    main()
