services:
  configs:
    service: {}
    workflow: {}
    pools: {}
    podTemplates: {}
    resourceValidations: {}
    backends: {}
    backendTests: {}
    groupTemplates: {}
    roles: {}
    secretRefs: []
