#!/bin/bash
# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

set -e

OSMO_CLI_INSTALL_PATH="/usr/local/osmo"
OSMO_CLI_SYMLINK_PATH="/usr/local/bin/osmo"
OSMO_CLI_AUTOCOMPLETE_PATH="/usr/local/share/zsh/site-functions/_osmo"

# Remove previous installation if it exists
if [ -e "$OSMO_CLI_INSTALL_PATH" ]; then
    rm -rf "$OSMO_CLI_INSTALL_PATH"
fi

# Remove previous symlink if it exists
if [ -L "$OSMO_CLI_SYMLINK_PATH" ]; then
    rm -f "$OSMO_CLI_SYMLINK_PATH"
fi

# Remove previous zsh completion file
if [ -f "$OSMO_CLI_AUTOCOMPLETE_PATH" ]; then
    rm -f "$OSMO_CLI_AUTOCOMPLETE_PATH"
fi

exit 0
