// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: src/proto/operator/messages.proto

package operator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListenerMessage_MessageType int32

const (
	ListenerMessage_unspecified ListenerMessage_MessageType = 0
	ListenerMessage_ack         ListenerMessage_MessageType = 1
	ListenerMessage_update_pod  ListenerMessage_MessageType = 2
)

// Enum value maps for ListenerMessage_MessageType.
var (
	ListenerMessage_MessageType_name = map[int32]string{
		0: "unspecified",
		1: "ack",
		2: "update_pod",
	}
	ListenerMessage_MessageType_value = map[string]int32{
		"unspecified": 0,
		"ack":         1,
		"update_pod":  2,
	}
)

func (x ListenerMessage_MessageType) Enum() *ListenerMessage_MessageType {
	p := new(ListenerMessage_MessageType)
	*p = x
	return p
}

func (x ListenerMessage_MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListenerMessage_MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_src_proto_operator_messages_proto_enumTypes[0].Descriptor()
}

func (ListenerMessage_MessageType) Type() protoreflect.EnumType {
	return &file_src_proto_operator_messages_proto_enumTypes[0]
}

func (x ListenerMessage_MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListenerMessage_MessageType.Descriptor instead.
func (ListenerMessage_MessageType) EnumDescriptor() ([]byte, []int) {
	return file_src_proto_operator_messages_proto_rawDescGZIP(), []int{0, 0}
}

type ListenerMessage struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Type          ListenerMessage_MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=operator.ListenerMessage_MessageType" json:"type,omitempty"`
	Uuid          string                      `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Timestamp     string                      `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Body          string                      `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenerMessage) Reset() {
	*x = ListenerMessage{}
	mi := &file_src_proto_operator_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenerMessage) ProtoMessage() {}

func (x *ListenerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_operator_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenerMessage.ProtoReflect.Descriptor instead.
func (*ListenerMessage) Descriptor() ([]byte, []int) {
	return file_src_proto_operator_messages_proto_rawDescGZIP(), []int{0}
}

func (x *ListenerMessage) GetType() ListenerMessage_MessageType {
	if x != nil {
		return x.Type
	}
	return ListenerMessage_unspecified
}

func (x *ListenerMessage) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ListenerMessage) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ListenerMessage) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type ConditionMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        bool                   `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConditionMessage) Reset() {
	*x = ConditionMessage{}
	mi := &file_src_proto_operator_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConditionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionMessage) ProtoMessage() {}

func (x *ConditionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_operator_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionMessage.ProtoReflect.Descriptor instead.
func (*ConditionMessage) Descriptor() ([]byte, []int) {
	return file_src_proto_operator_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ConditionMessage) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ConditionMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConditionMessage) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ConditionMessage) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *ConditionMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type UpdatePodBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowUuid  string                 `protobuf:"bytes,1,opt,name=workflow_uuid,json=workflowUuid,proto3" json:"workflow_uuid,omitempty"`
	TaskUuid      string                 `protobuf:"bytes,2,opt,name=task_uuid,json=taskUuid,proto3" json:"task_uuid,omitempty"`
	RetryId       int32                  `protobuf:"varint,3,opt,name=retry_id,json=retryId,proto3" json:"retry_id,omitempty"`
	Container     string                 `protobuf:"bytes,4,opt,name=container,proto3" json:"container,omitempty"`
	Node          string                 `protobuf:"bytes,5,opt,name=node,proto3" json:"node,omitempty"`
	PodIp         string                 `protobuf:"bytes,6,opt,name=pod_ip,json=podIp,proto3" json:"pod_ip,omitempty"`
	Message       string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	ExitCode      int32                  `protobuf:"varint,9,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Backend       string                 `protobuf:"bytes,10,opt,name=backend,proto3" json:"backend,omitempty"`
	Conditions    []*ConditionMessage    `protobuf:"bytes,11,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePodBody) Reset() {
	*x = UpdatePodBody{}
	mi := &file_src_proto_operator_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePodBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePodBody) ProtoMessage() {}

func (x *UpdatePodBody) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_operator_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePodBody.ProtoReflect.Descriptor instead.
func (*UpdatePodBody) Descriptor() ([]byte, []int) {
	return file_src_proto_operator_messages_proto_rawDescGZIP(), []int{2}
}

func (x *UpdatePodBody) GetWorkflowUuid() string {
	if x != nil {
		return x.WorkflowUuid
	}
	return ""
}

func (x *UpdatePodBody) GetTaskUuid() string {
	if x != nil {
		return x.TaskUuid
	}
	return ""
}

func (x *UpdatePodBody) GetRetryId() int32 {
	if x != nil {
		return x.RetryId
	}
	return 0
}

func (x *UpdatePodBody) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *UpdatePodBody) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *UpdatePodBody) GetPodIp() string {
	if x != nil {
		return x.PodIp
	}
	return ""
}

func (x *UpdatePodBody) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdatePodBody) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdatePodBody) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *UpdatePodBody) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *UpdatePodBody) GetConditions() []*ConditionMessage {
	if x != nil {
		return x.Conditions
	}
	return nil
}

var File_src_proto_operator_messages_proto protoreflect.FileDescriptor

const file_src_proto_operator_messages_proto_rawDesc = "" +
	"\n" +
	"!src/proto/operator/messages.proto\x12\boperator\"\xcb\x01\n" +
	"\x0fListenerMessage\x129\n" +
	"\x04type\x18\x01 \x01(\x0e2%.operator.ListenerMessage.MessageTypeR\x04type\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\"7\n" +
	"\vMessageType\x12\x0f\n" +
	"\vunspecified\x10\x00\x12\a\n" +
	"\x03ack\x10\x01\x12\x0e\n" +
	"\n" +
	"update_pod\x10\x02\"\x8e\x01\n" +
	"\x10ConditionMessage\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\x12\x16\n" +
	"\x06status\x18\x04 \x01(\bR\x06status\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\"\xda\x02\n" +
	"\rUpdatePodBody\x12#\n" +
	"\rworkflow_uuid\x18\x01 \x01(\tR\fworkflowUuid\x12\x1b\n" +
	"\ttask_uuid\x18\x02 \x01(\tR\btaskUuid\x12\x19\n" +
	"\bretry_id\x18\x03 \x01(\x05R\aretryId\x12\x1c\n" +
	"\tcontainer\x18\x04 \x01(\tR\tcontainer\x12\x12\n" +
	"\x04node\x18\x05 \x01(\tR\x04node\x12\x15\n" +
	"\x06pod_ip\x18\x06 \x01(\tR\x05podIp\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1b\n" +
	"\texit_code\x18\t \x01(\x05R\bexitCode\x12\x18\n" +
	"\abackend\x18\n" +
	" \x01(\tR\abackend\x12:\n" +
	"\n" +
	"conditions\x18\v \x03(\v2\x1a.operator.ConditionMessageR\n" +
	"conditionsB1Z/go.corp.nvidia.com/osmo/proto/operator;operatorb\x06proto3"

var (
	file_src_proto_operator_messages_proto_rawDescOnce sync.Once
	file_src_proto_operator_messages_proto_rawDescData []byte
)

func file_src_proto_operator_messages_proto_rawDescGZIP() []byte {
	file_src_proto_operator_messages_proto_rawDescOnce.Do(func() {
		file_src_proto_operator_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_proto_operator_messages_proto_rawDesc), len(file_src_proto_operator_messages_proto_rawDesc)))
	})
	return file_src_proto_operator_messages_proto_rawDescData
}

var file_src_proto_operator_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_src_proto_operator_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_src_proto_operator_messages_proto_goTypes = []any{
	(ListenerMessage_MessageType)(0), // 0: operator.ListenerMessage.MessageType
	(*ListenerMessage)(nil),          // 1: operator.ListenerMessage
	(*ConditionMessage)(nil),         // 2: operator.ConditionMessage
	(*UpdatePodBody)(nil),            // 3: operator.UpdatePodBody
}
var file_src_proto_operator_messages_proto_depIdxs = []int32{
	0, // 0: operator.ListenerMessage.type:type_name -> operator.ListenerMessage.MessageType
	2, // 1: operator.UpdatePodBody.conditions:type_name -> operator.ConditionMessage
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_src_proto_operator_messages_proto_init() }
func file_src_proto_operator_messages_proto_init() {
	if File_src_proto_operator_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_proto_operator_messages_proto_rawDesc), len(file_src_proto_operator_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_proto_operator_messages_proto_goTypes,
		DependencyIndexes: file_src_proto_operator_messages_proto_depIdxs,
		EnumInfos:         file_src_proto_operator_messages_proto_enumTypes,
		MessageInfos:      file_src_proto_operator_messages_proto_msgTypes,
	}.Build()
	File_src_proto_operator_messages_proto = out.File
	file_src_proto_operator_messages_proto_goTypes = nil
	file_src_proto_operator_messages_proto_depIdxs = nil
}
