// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: src/proto/operator/services.proto

package operator

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_src_proto_operator_services_proto protoreflect.FileDescriptor

const file_src_proto_operator_services_proto_rawDesc = "" +
	"\n" +
	"!src/proto/operator/services.proto\x12\boperator\x1a!src/proto/operator/messages.proto2e\n" +
	"\x0fListenerService\x12R\n" +
	"\x16WorkflowListenerStream\x12\x19.operator.ListenerMessage\x1a\x19.operator.ListenerMessage(\x010\x01B1Z/go.corp.nvidia.com/osmo/proto/operator;operatorb\x06proto3"

var file_src_proto_operator_services_proto_goTypes = []any{
	(*ListenerMessage)(nil), // 0: operator.ListenerMessage
}
var file_src_proto_operator_services_proto_depIdxs = []int32{
	0, // 0: operator.ListenerService.WorkflowListenerStream:input_type -> operator.ListenerMessage
	0, // 1: operator.ListenerService.WorkflowListenerStream:output_type -> operator.ListenerMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_proto_operator_services_proto_init() }
func file_src_proto_operator_services_proto_init() {
	if File_src_proto_operator_services_proto != nil {
		return
	}
	file_src_proto_operator_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_proto_operator_services_proto_rawDesc), len(file_src_proto_operator_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_proto_operator_services_proto_goTypes,
		DependencyIndexes: file_src_proto_operator_services_proto_depIdxs,
	}.Build()
	File_src_proto_operator_services_proto = out.File
	file_src_proto_operator_services_proto_goTypes = nil
	file_src_proto_operator_services_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ListenerServiceClient is the client API for ListenerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ListenerServiceClient interface {
	WorkflowListenerStream(ctx context.Context, opts ...grpc.CallOption) (ListenerService_WorkflowListenerStreamClient, error)
}

type listenerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewListenerServiceClient(cc grpc.ClientConnInterface) ListenerServiceClient {
	return &listenerServiceClient{cc}
}

func (c *listenerServiceClient) WorkflowListenerStream(ctx context.Context, opts ...grpc.CallOption) (ListenerService_WorkflowListenerStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ListenerService_serviceDesc.Streams[0], "/operator.ListenerService/WorkflowListenerStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &listenerServiceWorkflowListenerStreamClient{stream}
	return x, nil
}

type ListenerService_WorkflowListenerStreamClient interface {
	Send(*ListenerMessage) error
	Recv() (*ListenerMessage, error)
	grpc.ClientStream
}

type listenerServiceWorkflowListenerStreamClient struct {
	grpc.ClientStream
}

func (x *listenerServiceWorkflowListenerStreamClient) Send(m *ListenerMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *listenerServiceWorkflowListenerStreamClient) Recv() (*ListenerMessage, error) {
	m := new(ListenerMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ListenerServiceServer is the server API for ListenerService service.
type ListenerServiceServer interface {
	WorkflowListenerStream(ListenerService_WorkflowListenerStreamServer) error
}

// UnimplementedListenerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedListenerServiceServer struct {
}

func (*UnimplementedListenerServiceServer) WorkflowListenerStream(ListenerService_WorkflowListenerStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method WorkflowListenerStream not implemented")
}

func RegisterListenerServiceServer(s *grpc.Server, srv ListenerServiceServer) {
	s.RegisterService(&_ListenerService_serviceDesc, srv)
}

func _ListenerService_WorkflowListenerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ListenerServiceServer).WorkflowListenerStream(&listenerServiceWorkflowListenerStreamServer{stream})
}

type ListenerService_WorkflowListenerStreamServer interface {
	Send(*ListenerMessage) error
	Recv() (*ListenerMessage, error)
	grpc.ServerStream
}

type listenerServiceWorkflowListenerStreamServer struct {
	grpc.ServerStream
}

func (x *listenerServiceWorkflowListenerStreamServer) Send(m *ListenerMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *listenerServiceWorkflowListenerStreamServer) Recv() (*ListenerMessage, error) {
	m := new(ListenerMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ListenerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "operator.ListenerService",
	HandlerType: (*ListenerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WorkflowListenerStream",
			Handler:       _ListenerService_WorkflowListenerStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "src/proto/operator/services.proto",
}
