// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: src/proto/operator/services.proto

package operator

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitBackendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InitBody      *InitBody              `protobuf:"bytes,1,opt,name=init_body,json=initBody,proto3" json:"init_body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitBackendRequest) Reset() {
	*x = InitBackendRequest{}
	mi := &file_src_proto_operator_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitBackendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitBackendRequest) ProtoMessage() {}

func (x *InitBackendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_operator_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitBackendRequest.ProtoReflect.Descriptor instead.
func (*InitBackendRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_operator_services_proto_rawDescGZIP(), []int{0}
}

func (x *InitBackendRequest) GetInitBody() *InitBody {
	if x != nil {
		return x.InitBody
	}
	return nil
}

type InitBackendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitBackendResponse) Reset() {
	*x = InitBackendResponse{}
	mi := &file_src_proto_operator_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitBackendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitBackendResponse) ProtoMessage() {}

func (x *InitBackendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_operator_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitBackendResponse.ProtoReflect.Descriptor instead.
func (*InitBackendResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_operator_services_proto_rawDescGZIP(), []int{1}
}

func (x *InitBackendResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InitBackendResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_src_proto_operator_services_proto protoreflect.FileDescriptor

const file_src_proto_operator_services_proto_rawDesc = "" +
	"\n" +
	"!src/proto/operator/services.proto\x12\boperator\x1a!src/proto/operator/messages.proto\"E\n" +
	"\x12InitBackendRequest\x12/\n" +
	"\tinit_body\x18\x01 \x01(\v2\x12.operator.InitBodyR\binitBody\"I\n" +
	"\x13InitBackendResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb1\x01\n" +
	"\x0fListenerService\x12R\n" +
	"\x16WorkflowListenerStream\x12\x19.operator.ListenerMessage\x1a\x19.operator.ListenerMessage(\x010\x01\x12J\n" +
	"\vInitBackend\x12\x1c.operator.InitBackendRequest\x1a\x1d.operator.InitBackendResponseB1Z/go.corp.nvidia.com/osmo/proto/operator;operatorb\x06proto3"

var (
	file_src_proto_operator_services_proto_rawDescOnce sync.Once
	file_src_proto_operator_services_proto_rawDescData []byte
)

func file_src_proto_operator_services_proto_rawDescGZIP() []byte {
	file_src_proto_operator_services_proto_rawDescOnce.Do(func() {
		file_src_proto_operator_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_proto_operator_services_proto_rawDesc), len(file_src_proto_operator_services_proto_rawDesc)))
	})
	return file_src_proto_operator_services_proto_rawDescData
}

var file_src_proto_operator_services_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_proto_operator_services_proto_goTypes = []any{
	(*InitBackendRequest)(nil),  // 0: operator.InitBackendRequest
	(*InitBackendResponse)(nil), // 1: operator.InitBackendResponse
	(*InitBody)(nil),            // 2: operator.InitBody
	(*ListenerMessage)(nil),     // 3: operator.ListenerMessage
}
var file_src_proto_operator_services_proto_depIdxs = []int32{
	2, // 0: operator.InitBackendRequest.init_body:type_name -> operator.InitBody
	3, // 1: operator.ListenerService.WorkflowListenerStream:input_type -> operator.ListenerMessage
	0, // 2: operator.ListenerService.InitBackend:input_type -> operator.InitBackendRequest
	3, // 3: operator.ListenerService.WorkflowListenerStream:output_type -> operator.ListenerMessage
	1, // 4: operator.ListenerService.InitBackend:output_type -> operator.InitBackendResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_src_proto_operator_services_proto_init() }
func file_src_proto_operator_services_proto_init() {
	if File_src_proto_operator_services_proto != nil {
		return
	}
	file_src_proto_operator_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_proto_operator_services_proto_rawDesc), len(file_src_proto_operator_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_proto_operator_services_proto_goTypes,
		DependencyIndexes: file_src_proto_operator_services_proto_depIdxs,
		MessageInfos:      file_src_proto_operator_services_proto_msgTypes,
	}.Build()
	File_src_proto_operator_services_proto = out.File
	file_src_proto_operator_services_proto_goTypes = nil
	file_src_proto_operator_services_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ListenerServiceClient is the client API for ListenerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ListenerServiceClient interface {
	WorkflowListenerStream(ctx context.Context, opts ...grpc.CallOption) (ListenerService_WorkflowListenerStreamClient, error)
	InitBackend(ctx context.Context, in *InitBackendRequest, opts ...grpc.CallOption) (*InitBackendResponse, error)
}

type listenerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewListenerServiceClient(cc grpc.ClientConnInterface) ListenerServiceClient {
	return &listenerServiceClient{cc}
}

func (c *listenerServiceClient) WorkflowListenerStream(ctx context.Context, opts ...grpc.CallOption) (ListenerService_WorkflowListenerStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ListenerService_serviceDesc.Streams[0], "/operator.ListenerService/WorkflowListenerStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &listenerServiceWorkflowListenerStreamClient{stream}
	return x, nil
}

type ListenerService_WorkflowListenerStreamClient interface {
	Send(*ListenerMessage) error
	Recv() (*ListenerMessage, error)
	grpc.ClientStream
}

type listenerServiceWorkflowListenerStreamClient struct {
	grpc.ClientStream
}

func (x *listenerServiceWorkflowListenerStreamClient) Send(m *ListenerMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *listenerServiceWorkflowListenerStreamClient) Recv() (*ListenerMessage, error) {
	m := new(ListenerMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *listenerServiceClient) InitBackend(ctx context.Context, in *InitBackendRequest, opts ...grpc.CallOption) (*InitBackendResponse, error) {
	out := new(InitBackendResponse)
	err := c.cc.Invoke(ctx, "/operator.ListenerService/InitBackend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListenerServiceServer is the server API for ListenerService service.
type ListenerServiceServer interface {
	WorkflowListenerStream(ListenerService_WorkflowListenerStreamServer) error
	InitBackend(context.Context, *InitBackendRequest) (*InitBackendResponse, error)
}

// UnimplementedListenerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedListenerServiceServer struct {
}

func (*UnimplementedListenerServiceServer) WorkflowListenerStream(ListenerService_WorkflowListenerStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method WorkflowListenerStream not implemented")
}
func (*UnimplementedListenerServiceServer) InitBackend(context.Context, *InitBackendRequest) (*InitBackendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitBackend not implemented")
}

func RegisterListenerServiceServer(s *grpc.Server, srv ListenerServiceServer) {
	s.RegisterService(&_ListenerService_serviceDesc, srv)
}

func _ListenerService_WorkflowListenerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ListenerServiceServer).WorkflowListenerStream(&listenerServiceWorkflowListenerStreamServer{stream})
}

type ListenerService_WorkflowListenerStreamServer interface {
	Send(*ListenerMessage) error
	Recv() (*ListenerMessage, error)
	grpc.ServerStream
}

type listenerServiceWorkflowListenerStreamServer struct {
	grpc.ServerStream
}

func (x *listenerServiceWorkflowListenerStreamServer) Send(m *ListenerMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *listenerServiceWorkflowListenerStreamServer) Recv() (*ListenerMessage, error) {
	m := new(ListenerMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ListenerService_InitBackend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitBackendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListenerServiceServer).InitBackend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/operator.ListenerService/InitBackend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListenerServiceServer).InitBackend(ctx, req.(*InitBackendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ListenerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "operator.ListenerService",
	HandlerType: (*ListenerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitBackend",
			Handler:    _ListenerService_InitBackend_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WorkflowListenerStream",
			Handler:       _ListenerService_WorkflowListenerStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "src/proto/operator/services.proto",
}
