#!/bin/bash
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Azure Blob storage backend for configure-storage.sh.
# Expects KUBECTL, NAMESPACE, OUTPUT_VALUES in env (set by the dispatcher).
#
# Resolves credentials in priority order:
#   1. STORAGE_ACCOUNT + STORAGE_KEY env vars (preferred for BYO Azure SA)
#   2. osmo Azure TF outputs (storage_account, storage_account_key)
#
# Creates 3 K8s Secrets (workflow-{data,log,app}-cred) populated with the
# Azure connection string and emits a Helm values fragment to $OUTPUT_VALUES.

set -euo pipefail

KUBECTL="${KUBECTL:-kubectl}"
NAMESPACE="${NAMESPACE:?NAMESPACE not set}"
OUTPUT_VALUES="${OUTPUT_VALUES:?OUTPUT_VALUES not set}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TF_DIR="${TF_DIR:-$SCRIPT_DIR/../../terraform/azure/example}"

CONTAINER_NAME="${AZURE_CONTAINER_NAME:-osmo-workflows}"

# 1. Resolve credentials
if [[ -n "${STORAGE_ACCOUNT:-}" && -n "${STORAGE_KEY:-}" ]]; then
    echo "[INFO] Using Azure Storage credentials from env vars (STORAGE_ACCOUNT, STORAGE_KEY)"
elif command -v terraform &>/dev/null && [[ -d "$TF_DIR" ]] \
        && terraform -chdir="$TF_DIR" output storage_account &>/dev/null; then
    STORAGE_ACCOUNT=$(terraform -chdir="$TF_DIR" output -raw storage_account)
    STORAGE_KEY=$(terraform -chdir="$TF_DIR" output -raw storage_account_key)
    echo "[INFO] Using Azure Storage credentials from osmo Azure TF outputs"
else
    cat >&2 <<'MSG'
[ERROR] Azure Blob backend requires credentials. Provide either:

  STORAGE_ACCOUNT=<account_name>
  STORAGE_KEY=<account_key>

or run osmo Azure terraform with `storage_account_enabled=true` and let the
script read its outputs from terraform/azure/example/.
MSG
    exit 1
fi

# Build the standard Azure Blob connection string. The chart's secret-loader
# uses this as the access_key field (Azure-style auth).
CONN_STR="DefaultEndpointsProtocol=https;AccountName=${STORAGE_ACCOUNT};AccountKey=${STORAGE_KEY};EndpointSuffix=core.windows.net"
ENDPOINT="az://${CONTAINER_NAME}@${STORAGE_ACCOUNT}"

# 2. Ensure the container exists. Best-effort via az if available; otherwise
# trust that the TF or admin pre-created it.
if command -v az &>/dev/null; then
    echo "[INFO] Ensuring Azure container $CONTAINER_NAME exists"
    az storage container create \
        --name "$CONTAINER_NAME" \
        --account-name "$STORAGE_ACCOUNT" \
        --account-key "$STORAGE_KEY" \
        --output none 2>/dev/null \
        || echo "[WARN] az container create failed; container may already exist or perms missing"
else
    echo "[INFO] az CLI not available — assuming container $CONTAINER_NAME already exists"
fi

# 3. Create K8s Secrets — same payload shape as MinIO/BYO so the chart's
# Secret loader can be backend-agnostic (access_key_id + access_key).
create_cred_secret() {
    local secret_name="$1"
    $KUBECTL create secret generic "$secret_name" -n "$NAMESPACE" \
        --from-literal=access_key_id="$STORAGE_ACCOUNT" \
        --from-literal=access_key="$CONN_STR" \
        --from-literal=endpoint="$ENDPOINT" \
        --from-literal=region="${STORAGE_LOCATION:-eastus2}" \
        --from-literal=override_url="" \
        --dry-run=client -o yaml | $KUBECTL apply -f -
}

create_cred_secret "osmo-workflow-data-cred"
create_cred_secret "osmo-workflow-log-cred"
create_cred_secret "osmo-workflow-app-cred"

# 4. Emit Helm values fragment — backend-specific bits only.
# All structural config (configs.enabled, service_base_url, backends.default,
# secretRefs, workflow_log/app credential refs, backend_images skeleton) lives
# in values/service.yaml; deploy-k8s.sh fills per-cluster bits via --set. Only
# `workflow_data.base_url` (Azure Blob az:// URL) is genuinely backend-specific.
cat > "$OUTPUT_VALUES" <<EOF
# Generated by configure-storage.sh --backend azure-blob — DO NOT EDIT.
services:
  configs:
    workflow:
      workflow_data:
        base_url: $ENDPOINT
EOF

echo "[INFO] Azure Blob storage configured:"
echo "       account:    $STORAGE_ACCOUNT"
echo "       container:  $CONTAINER_NAME"
echo "       endpoint:   $ENDPOINT"
echo "       secrets:    osmo-workflow-{data,log,app}-cred in $NAMESPACE"
echo "       values:     $OUTPUT_VALUES"
