#!/bin/bash
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Azure Blob storage backend for configure-storage.sh.
# Two auth modes:
#
#   --auth-method static (default)
#     Connection-string auth. Resolves credentials from:
#       1. STORAGE_ACCOUNT + STORAGE_KEY env vars
#       2. osmo Azure TF outputs (storage_account, storage_account_key)
#     Creates 3 K8s Secrets with the connection string. Best-effort container
#     creation via `az` if available.
#
#   --auth-method workload-identity (AKS workload identity)
#     Caller has provisioned a User-Assigned Managed Identity (UAMI) with
#     `Storage Blob Data Contributor` on the storage account, and a
#     federated credential that links the UAMI to the AKS OIDC issuer +
#     namespace + chart-managed ServiceAccount. Required env:
#       WORKLOAD_IDENTITY_CLIENT_ID  (UAMI client ID)
#       STORAGE_ACCOUNT              (storage account name)
#     Optional: AZURE_CONTAINER_NAME (default: osmo-workflows)
#     Script writes NO Secrets; emits a values fragment with
#     DefaultDataCredential shape + the SA annotation +
#     `azure.workload.identity/use: "true"` pod labels on the components that
#     do cloud I/O (worker, agent, logger, service, delayedJobMonitor).

set -euo pipefail

KUBECTL="${KUBECTL:-kubectl}"
NAMESPACE="${NAMESPACE:?NAMESPACE not set}"
OUTPUT_VALUES="${OUTPUT_VALUES:?OUTPUT_VALUES not set}"
AUTH_METHOD="${AUTH_METHOD:-static}"
NGC_SECRET_NAME="${NGC_SECRET_NAME:-nvcr-secret}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/common.sh"
TF_DIR="${TF_DIR:-$SCRIPT_DIR/../../terraform/azure/example}"

CONTAINER_NAME="${AZURE_CONTAINER_NAME:-${OSMO_WORKFLOW_BUCKET:-osmo-workflows}}"

if [[ "$AUTH_METHOD" == "workload-identity" ]]; then
    # ─── Azure WI path ────────────────────────────────────────────────────
    if [[ -z "${WORKLOAD_IDENTITY_CLIENT_ID:-}" || -z "${STORAGE_ACCOUNT:-}" ]]; then
        cat >&2 <<'MSG'
[ERROR] Azure Blob backend (workload-identity) requires:
  WORKLOAD_IDENTITY_CLIENT_ID  e.g. 11111111-2222-3333-4444-555555555555  (UAMI client ID)
  STORAGE_ACCOUNT              e.g. mystorageacct                          (account name)

Optional:
  AZURE_CONTAINER_NAME         (default: osmo-workflows)
MSG
        exit 1
    fi

    # OSMO storage SDK expects azure://account/container (per
    # src/lib/data/storage/constants/constants.py AZURE_REGEX). Other Azure
    # tooling uses az://container@account, but that's not what osmo parses.
    ENDPOINT="azure://${STORAGE_ACCOUNT}/${CONTAINER_NAME}"

    cat > "$OUTPUT_VALUES" <<EOF
# Generated by configure-storage.sh --backend azure-blob --auth-method workload-identity
# DO NOT EDIT.
#
# AKS Workload Identity: caller has provisioned the UAMI + RBAC on the storage
# account + federated credential linking UAMI -> AKS OIDC issuer + namespace
# + chart-managed ServiceAccount. The chart adds the SA annotation; the AKS
# WI mutating webhook injects the OIDC token volume into pods labeled with
# `azure.workload.identity/use: "true"`. Azure SDK's DefaultAzureCredential
# resolves the token at runtime — no static creds needed.
serviceAccount:
  create: true
  annotations:
    azure.workload.identity/client-id: "$WORKLOAD_IDENTITY_CLIENT_ID"

services:
  # extraPodLabels — required by the AKS WI webhook to inject the OIDC token
  # volume. Applied to every component that talks to Azure Blob storage.
  worker:
    extraPodLabels:
      azure.workload.identity/use: "true"
  agent:
    extraPodLabels:
      azure.workload.identity/use: "true"
  logger:
    extraPodLabels:
      azure.workload.identity/use: "true"
  service:
    extraPodLabels:
      azure.workload.identity/use: "true"
  delayedJobMonitor:
    extraPodLabels:
      azure.workload.identity/use: "true"

  configs:
    # secretRefs unchanged from values/service.yaml — only the NGC pull
    # secret needs mounting; no workflow-data K8s Secrets exist in WI mode.
    workflow:
      workflow_data:
        credential:
          # DefaultDataCredential shape — endpoint only, no secretName.
          # Azure SDK resolves creds via the SA's WI token (DefaultAzureCredential).
          endpoint: "$ENDPOINT"
        base_url: "$ENDPOINT"
      workflow_log:
        credential:
          endpoint: "$ENDPOINT"
      workflow_app:
        credential:
          endpoint: "$ENDPOINT"
EOF

    echo "[INFO] Azure Blob storage configured (workload-identity):"
    echo "       account:        $STORAGE_ACCOUNT"
    echo "       container:      $CONTAINER_NAME"
    echo "       endpoint:       $ENDPOINT"
    echo "       UAMI client-id: $WORKLOAD_IDENTITY_CLIENT_ID"
    echo "       SA mode:        chart creates SA with azure.workload.identity/client-id annotation"
    echo "       values:         $OUTPUT_VALUES"
    exit 0
fi

# ─── static auth (default) ────────────────────────────────────────────────
if [[ -n "${STORAGE_ACCOUNT:-}" && -n "${STORAGE_KEY:-}" ]]; then
    echo "[INFO] Using Azure Storage credentials from env vars (STORAGE_ACCOUNT, STORAGE_KEY)"
elif command -v terraform &>/dev/null && [[ -d "$TF_DIR" ]] \
        && terraform -chdir="$TF_DIR" output storage_account &>/dev/null; then
    STORAGE_ACCOUNT=$(terraform -chdir="$TF_DIR" output -raw storage_account)
    STORAGE_KEY=$(terraform -chdir="$TF_DIR" output -raw storage_account_key)
    echo "[INFO] Using Azure Storage credentials from osmo Azure TF outputs"
else
    cat >&2 <<'MSG'
[ERROR] Azure Blob backend (static auth) requires credentials. Provide either:

  STORAGE_ACCOUNT=<account_name>
  STORAGE_KEY=<account_key>

or run osmo Azure terraform with `storage_account_enabled=true` and let the
script read its outputs from terraform/azure/example/.

For workload-identity mode, set --auth-method workload-identity and provide
WORKLOAD_IDENTITY_CLIENT_ID instead of STORAGE_KEY.
MSG
    exit 1
fi

# Build the standard Azure Blob connection string. AZURE_ENDPOINT_SUFFIX is
# `core.windows.net` for public Azure (default), `core.usgovcloudapi.net` for
# Azure Government, `core.chinacloudapi.cn` for Azure China.
CONN_STR="DefaultEndpointsProtocol=https;AccountName=${STORAGE_ACCOUNT};AccountKey=${STORAGE_KEY};EndpointSuffix=${AZURE_ENDPOINT_SUFFIX:-core.windows.net}"
# OSMO storage SDK expects azure://account/container (per AZURE_REGEX in
# src/lib/data/storage/constants/constants.py).
ENDPOINT="azure://${STORAGE_ACCOUNT}/${CONTAINER_NAME}"

# Ensure the container exists. Best-effort via az if available.
if command -v az &>/dev/null; then
    echo "[INFO] Ensuring Azure container $CONTAINER_NAME exists"
    az storage container create \
        --name "$CONTAINER_NAME" \
        --account-name "$STORAGE_ACCOUNT" \
        --account-key "$STORAGE_KEY" \
        --output none 2>/dev/null \
        || echo "[WARN] az container create failed; container may already exist or perms missing"
else
    echo "[INFO] az CLI not available — assuming container $CONTAINER_NAME already exists"
fi

create_workflow_cred_secrets \
    "$STORAGE_ACCOUNT" "$CONN_STR" "$ENDPOINT" "${STORAGE_LOCATION:-eastus2}" ""

emit_static_values_fragment azure-blob "$ENDPOINT"

echo "[INFO] Azure Blob storage configured (static auth):"
echo "       account:    $STORAGE_ACCOUNT"
echo "       container:  $CONTAINER_NAME"
echo "       endpoint:   $ENDPOINT"
echo "       secrets:    osmo-workflow-{data,log,app}-cred in $NAMESPACE"
echo "       values:     $OUTPUT_VALUES"
