"""
SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION. All rights reserved.
SPDX-License-Identifier: Apache-2.0
"""

sh_test(
    name = "minio_addressing_style_test",
    srcs = ["tests/minio_addressing_style_test.sh"],
    data = [
        "common.sh",
        "minio.sh",
    ],
)

sh_test(
    name = "rustfs_addressing_style_test",
    srcs = ["tests/rustfs_addressing_style_test.sh"],
    data = [
        "common.sh",
        "rustfs.sh",
    ],
)
