#!/bin/bash
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# BYO (bring-your-own) S3-compatible storage backend for configure-storage.sh.
# No resource creation — the user has already provisioned the bucket and
# credentials. This script just registers them as K8s Secrets and emits the
# values fragment.
#
# Required env vars:
#   STORAGE_ACCESS_KEY_ID   — access key id
#   STORAGE_ACCESS_KEY      — secret access key
#   STORAGE_ENDPOINT        — bucket endpoint (e.g. s3://my-bucket)
#
# Optional env vars:
#   STORAGE_REGION          — default: us-east-1
#   STORAGE_OVERRIDE_URL    — endpoint URL (e.g. https://s3.us-east-1.amazonaws.com,
#                             or a Ceph/Wasabi endpoint)

set -euo pipefail

KUBECTL="${KUBECTL:-kubectl}"
NAMESPACE="${NAMESPACE:?NAMESPACE not set}"
OUTPUT_VALUES="${OUTPUT_VALUES:?OUTPUT_VALUES not set}"

if [[ -z "${STORAGE_ACCESS_KEY_ID:-}" || -z "${STORAGE_ACCESS_KEY:-}" || -z "${STORAGE_ENDPOINT:-}" ]]; then
    cat >&2 <<'MSG'
[ERROR] BYO storage backend requires:
  STORAGE_ACCESS_KEY_ID
  STORAGE_ACCESS_KEY
  STORAGE_ENDPOINT (e.g. s3://my-bucket)

Optional:
  STORAGE_REGION       (default: us-east-1)
  STORAGE_OVERRIDE_URL (e.g. https://s3.us-east-1.amazonaws.com)
MSG
    exit 1
fi

REGION="${STORAGE_REGION:-us-east-1}"
OVERRIDE_URL="${STORAGE_OVERRIDE_URL:-}"

create_cred_secret() {
    local secret_name="$1"
    $KUBECTL create secret generic "$secret_name" -n "$NAMESPACE" \
        --from-literal=access_key_id="$STORAGE_ACCESS_KEY_ID" \
        --from-literal=access_key="$STORAGE_ACCESS_KEY" \
        --from-literal=endpoint="$STORAGE_ENDPOINT" \
        --from-literal=region="$REGION" \
        --from-literal=override_url="$OVERRIDE_URL" \
        --dry-run=client -o yaml | $KUBECTL apply -f -
}

create_cred_secret "osmo-workflow-data-cred"
create_cred_secret "osmo-workflow-log-cred"
create_cred_secret "osmo-workflow-app-cred"

cat > "$OUTPUT_VALUES" <<EOF
# Generated by configure-storage.sh --backend byo — DO NOT EDIT.
# All structural config lives in values/service.yaml; deploy-k8s.sh fills
# per-cluster bits via --set. Only the BYO bucket URL is backend-specific.
services:
  configs:
    workflow:
      workflow_data:
        base_url: $STORAGE_ENDPOINT
EOF

echo "[INFO] BYO storage configured:"
echo "       endpoint:    $STORAGE_ENDPOINT"
echo "       region:      $REGION"
echo "       override:    ${OVERRIDE_URL:-<none>}"
echo "       secrets:     osmo-workflow-{data,log,app}-cred in $NAMESPACE"
echo "       values:      $OUTPUT_VALUES"
