#!/bin/bash
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# BYO (bring-your-own) S3-compatible storage backend for configure-storage.sh.
# Two auth modes:
#
#   --auth-method static (default)
#     User has access keys. Script registers them as K8s Secrets and emits a
#     values fragment with `secretName` references. Required env:
#       STORAGE_ACCESS_KEY_ID, STORAGE_ACCESS_KEY, STORAGE_ENDPOINT
#     Optional: STORAGE_REGION, STORAGE_OVERRIDE_URL, STORAGE_ADDRESSING_STYLE
#
#   --auth-method workload-identity (AWS IRSA)
#     User has provisioned an IAM role with S3 access + an EKS OIDC trust
#     policy that admits the chart-managed ServiceAccount in the deploy
#     namespace. Script writes NO Secrets; emits a values fragment with
#     DefaultDataCredential shape (just `endpoint`) and the
#     `eks.amazonaws.com/role-arn` SA annotation. Required env:
#       WORKLOAD_IDENTITY_ROLE_ARN, STORAGE_ENDPOINT
#     Optional: STORAGE_REGION, STORAGE_OVERRIDE_URL, STORAGE_ADDRESSING_STYLE
#
# In both modes the user pre-provisions the bucket — this script never creates
# storage resources.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/common.sh"

KUBECTL="${KUBECTL:-kubectl}"
NAMESPACE="${NAMESPACE:?NAMESPACE not set}"
OUTPUT_VALUES="${OUTPUT_VALUES:?OUTPUT_VALUES not set}"
AUTH_METHOD="${AUTH_METHOD:-static}"
NGC_SECRET_NAME="${NGC_SECRET_NAME:-nvcr-secret}"

REGION="${STORAGE_REGION:-us-east-1}"
OVERRIDE_URL="${STORAGE_OVERRIDE_URL:-}"
ADDRESSING_STYLE="${STORAGE_ADDRESSING_STYLE:-}"
validate_addressing_style "$ADDRESSING_STYLE"

if [[ "$AUTH_METHOD" == "workload-identity" ]]; then
    # IRSA path — only need the bucket endpoint + the role ARN.
    if [[ -z "${WORKLOAD_IDENTITY_ROLE_ARN:-}" || -z "${STORAGE_ENDPOINT:-}" ]]; then
        cat >&2 <<'MSG'
[ERROR] BYO storage backend (workload-identity / AWS IRSA) requires:
  WORKLOAD_IDENTITY_ROLE_ARN  e.g. arn:aws:iam::123456789012:role/osmo-data-access
  STORAGE_ENDPOINT            e.g. s3://my-bucket

Optional:
  STORAGE_REGION              (default: us-east-1)
  STORAGE_OVERRIDE_URL        (e.g. for non-AWS S3-compatible endpoints)
  STORAGE_ADDRESSING_STYLE    (virtual|path|auto)
MSG
        exit 1
    fi

    cat > "$OUTPUT_VALUES" <<EOF
# Generated by configure-storage.sh --backend byo --auth-method workload-identity
# DO NOT EDIT.
#
# AWS IRSA: caller has provisioned the IAM role + S3 trust policy + bucket.
# Chart-managed SA gets the role-arn annotation; pods running under that SA
# receive an OIDC token via the standard IRSA env vars (AWS_ROLE_ARN,
# AWS_WEB_IDENTITY_TOKEN_FILE), which boto3's default credential chain picks
# up automatically. No K8s Secrets are created — the SDK resolves at runtime.
serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: "$WORKLOAD_IDENTITY_ROLE_ARN"

services:
  configs:
    # secretRefs unchanged from values/service.yaml — only the NGC pull
    # secret needs mounting; no workflow-data K8s Secrets exist in WI mode.
    workflow:
      workflow_data:
        credential:
          # DefaultDataCredential shape — endpoint only, no secretName.
          # Boto3 picks up creds via the IRSA token automount on the SA.
          endpoint: "$STORAGE_ENDPOINT"
          region: "$REGION"
$([[ -n "$OVERRIDE_URL" ]] && echo "          override_url: \"$OVERRIDE_URL\"")
$([[ -n "$ADDRESSING_STYLE" ]] && echo "          addressing_style: \"$ADDRESSING_STYLE\"")
        base_url: "$STORAGE_ENDPOINT"
      workflow_log:
        credential:
          endpoint: "$STORAGE_ENDPOINT"
          region: "$REGION"
$([[ -n "$OVERRIDE_URL" ]] && echo "          override_url: \"$OVERRIDE_URL\"")
$([[ -n "$ADDRESSING_STYLE" ]] && echo "          addressing_style: \"$ADDRESSING_STYLE\"")
      workflow_app:
        credential:
          endpoint: "$STORAGE_ENDPOINT"
          region: "$REGION"
$([[ -n "$OVERRIDE_URL" ]] && echo "          override_url: \"$OVERRIDE_URL\"")
$([[ -n "$ADDRESSING_STYLE" ]] && echo "          addressing_style: \"$ADDRESSING_STYLE\"")
EOF

    echo "[INFO] BYO storage configured (AWS IRSA / workload-identity):"
    echo "       role ARN:    $WORKLOAD_IDENTITY_ROLE_ARN"
    echo "       endpoint:    $STORAGE_ENDPOINT"
    echo "       region:      $REGION"
    echo "       addressing:  ${ADDRESSING_STYLE:-<default>}"
    echo "       SA mode:     chart creates SA with eks.amazonaws.com/role-arn annotation"
    echo "       values:      $OUTPUT_VALUES"
    exit 0
fi

# ─── static auth (default) ────────────────────────────────────────────────
if [[ -z "${STORAGE_ACCESS_KEY_ID:-}" || -z "${STORAGE_ACCESS_KEY:-}" || -z "${STORAGE_ENDPOINT:-}" ]]; then
    cat >&2 <<'MSG'
[ERROR] BYO storage backend (static auth) requires:
  STORAGE_ACCESS_KEY_ID
  STORAGE_ACCESS_KEY
  STORAGE_ENDPOINT (e.g. s3://my-bucket)

Optional:
  STORAGE_REGION       (default: us-east-1)
  STORAGE_OVERRIDE_URL (e.g. https://s3.us-east-1.amazonaws.com)
  STORAGE_ADDRESSING_STYLE (virtual|path|auto)

For workload-identity / IRSA mode, set --auth-method workload-identity and
provide WORKLOAD_IDENTITY_ROLE_ARN instead of access keys.
MSG
    exit 1
fi

create_workflow_cred_secrets \
    "$STORAGE_ACCESS_KEY_ID" "$STORAGE_ACCESS_KEY" "$STORAGE_ENDPOINT" "$REGION" "$OVERRIDE_URL" \
    "$ADDRESSING_STYLE"

emit_static_values_fragment byo "$STORAGE_ENDPOINT"

echo "[INFO] BYO storage configured (static auth):"
echo "       endpoint:    $STORAGE_ENDPOINT"
echo "       region:      $REGION"
echo "       override:    ${OVERRIDE_URL:-<none>}"
echo "       addressing:  ${ADDRESSING_STYLE:-<default>}"
echo "       secrets:     osmo-workflow-{data,log,app}-cred in $NAMESPACE"
echo "       values:      $OUTPUT_VALUES"
