# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Helpers shared by storage backend scripts (minio.sh, s3.sh, azure-blob.sh,
# byo.sh). Each backend resolves its own connection details, then calls the
# helpers below to register the K8s Secrets + emit the values fragment that
# deploy-k8s.sh layers into the helm install.

# Create the three K8s Secrets the OSMO storage SDK reads via
# services.configs.workflow.workflow_*.credential.secretName.
# Args: access_key_id access_key endpoint region override_url [addressing_style]
validate_addressing_style() {
    local addressing_style="${1:-}"
    case "$addressing_style" in
        ""|virtual|path|auto) ;;
        *)
            echo "[ERROR] Invalid addressing style '$addressing_style' (expected: virtual, path, or auto)" >&2
            exit 1
            ;;
    esac
}

create_workflow_cred_secrets() {
    local access_key_id="$1" access_key="$2" endpoint="$3" region="$4" override_url="$5"
    local addressing_style="${6:-}"
    validate_addressing_style "$addressing_style"
    local addressing_style_arg=()
    if [[ -n "$addressing_style" ]]; then
        addressing_style_arg=(--from-literal=addressing_style="$addressing_style")
    fi
    local name
    for name in osmo-workflow-data-cred osmo-workflow-log-cred osmo-workflow-app-cred; do
        $KUBECTL create secret generic "$name" -n "$NAMESPACE" \
            --from-literal=access_key_id="$access_key_id" \
            --from-literal=access_key="$access_key" \
            --from-literal=endpoint="$endpoint" \
            --from-literal=region="$region" \
            --from-literal=override_url="$override_url" \
            ${addressing_style_arg[@]+"${addressing_style_arg[@]}"} \
            --dry-run=client -o yaml | $KUBECTL apply -f -
    done
}

# Emit the static-auth Helm values fragment to $OUTPUT_VALUES. The chart's
# secretRefs default is empty; this fragment populates it with the workflow-
# cred secrets so the chart mounts them at /etc/osmo/secrets/<name>/. The NGC
# pull-secret entry is only included when NGC_SECRET_NAME is non-empty (caller
# opted in via --ngc-api-key, --ngc-secret-name, or NGC_SECRET_NAME env) —
# same gate the rest of the script uses for global.imagePullSecret and
# backend_images.credential, so no-opt-in deploys never reference a secret
# that won't exist.
# Args: backend_label (free text for the comment header) base_url
emit_static_values_fragment() {
    local backend_label="$1" base_url="$2"
    {
        cat <<EOF
# Generated by configure-storage.sh --backend $backend_label --auth-method static — DO NOT EDIT.
services:
  configs:
    secretRefs:
EOF
        if [[ -n "$NGC_SECRET_NAME" ]]; then
            echo "      - secretName: ${NGC_SECRET_NAME}"
        fi
        cat <<EOF
      - secretName: osmo-workflow-data-cred
      - secretName: osmo-workflow-log-cred
      - secretName: osmo-workflow-app-cred
    workflow:
      workflow_data:
        credential:
          secretName: osmo-workflow-data-cred
        base_url: $base_url
      workflow_log:
        credential:
          secretName: osmo-workflow-log-cred
      workflow_app:
        credential:
          secretName: osmo-workflow-app-cred
EOF
    } > "$OUTPUT_VALUES"
}
