# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.authz.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateway.fullname" . }}-authz
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
    {{- include "gateway.componentLabels" (dict "component" "authz" "context" .) | nindent 4 }}
spec:
  replicas: {{ .Values.authz.replicas }}
  selector:
    matchLabels:
      {{- include "gateway.componentLabels" (dict "component" "authz" "context" .) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gateway.componentLabels" (dict "component" "authz" "context" .) | nindent 8 }}
      annotations:
        {{- include "gateway.extra-annotations" .Values.authz | nindent 8 }}
    spec:
      {{- with .Values.authz.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.authz.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.global.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.global.imagePullSecret }}
      {{- end }}
      serviceAccountName: {{ include "gateway.serviceAccountName" (dict "serviceAccountName" .Values.authz.serviceAccountName "global" .Values.global) }}
      containers:
      - name: authz
        securityContext:
          {{- toYaml .Values.authz.securityContext | nindent 10 }}
        image: "{{ .Values.global.osmoImageLocation }}/{{ .Values.authz.imageName }}:{{ .Values.global.osmoImageTag }}"
        imagePullPolicy: {{ .Values.authz.imagePullPolicy }}
        args:
          - "--grpc-port={{ .Values.authz.grpcPort }}"
          - "--postgres-host={{ .Values.authz.postgres.serviceName }}"
          - "--postgres-port={{ .Values.authz.postgres.port }}"
          - "--postgres-database={{ .Values.authz.postgres.db }}"
          - "--postgres-user={{ .Values.authz.postgres.user }}"
          - "--postgres-ssl-mode={{ .Values.authz.postgres.sslMode }}"
          - "--postgres-max-conns={{ .Values.authz.postgres.maxConns }}"
          - "--postgres-min-conns={{ .Values.authz.postgres.minConns }}"
          - "--postgres-max-conn-lifetime={{ .Values.authz.postgres.maxConnLifetimeMin }}"
          - "--cache-ttl={{ .Values.authz.cache.ttl }}"
          - "--cache-max-size={{ .Values.authz.cache.maxSize }}"
          {{- if .Values.global.logs.enabled }}
          - "--log-dir=/logs"
          - "--log-name=authz_sidecar"
          {{- end }}
        env:
          {{- if .Values.authz.migration.enabled }}
          - name: OSMO_SCHEMA_VERSION
            value: {{ .Values.authz.migration.targetSchema }}
          {{- end }}
          {{- include "gateway.extra-env" .Values.authz | nindent 10 }}
          {{- if .Values.authz.postgres.password }}
          - name: OSMO_POSTGRES_PASSWORD
            value: {{ .Values.authz.postgres.password }}
          {{- else if .Values.authz.configFile.enabled }}
          - name: OSMO_POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: db-password
          - name: OSMO_REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-secret
                key: redis-password
          {{- end }}
        {{- if or .Values.global.logs.enabled .Values.authz.extraVolumeMounts }}
        volumeMounts:
          {{- if .Values.global.logs.enabled }}
          - name: logs
            mountPath: /logs
          {{- end }}
          {{- with .Values.authz.extraVolumeMounts }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- end }}
        {{- with .Values.authz.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.authz.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.authz.resources | nindent 10 }}
      volumes:
        {{- if .Values.global.logs.enabled }}
        - name: logs
          emptyDir: {}
        {{- end }}
        {{- with .Values.authz.extraVolumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}-authz
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
    {{- include "gateway.componentLabels" (dict "component" "authz" "context" .) | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.authz.grpcPort }}
      targetPort: {{ .Values.authz.grpcPort }}
      protocol: TCP
      name: grpc
  selector:
    {{- include "gateway.componentLabels" (dict "component" "authz" "context" .) | nindent 4 }}

{{- end }}
