# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.  # pylint: disable=line-too-long
# SPDX-License-Identifier: Apache-2.0
"""Create a pull request with AI-generated test files."""

import logging

from coverage_agent.state import CoverageState
from coverage_agent.tools.shell import run_shell

logger = logging.getLogger(__name__)


def _has_open_agent_pr() -> bool:
    """Check if there's already an open PR with the ai-generated label."""
    result = run_shell("gh pr list --label ai-generated --state open --json number --jq \"length\"")
    if result.returncode != 0:
        return False
    try:
        return int(result.stdout.strip()) > 0
    except ValueError:
        return False


def create_pr(state: CoverageState) -> CoverageState:
    """LangGraph node: create a git branch, commit generated tests, and open a PR."""
    if not state["generated_files"]:
        logger.info("No generated files passed validation and quality gate. Skipping PR.")
        return state

    if state.get("dry_run", False):
        logger.info("Dry run: would create PR with files: %s", state["generated_files"])
        return state

    if _has_open_agent_pr():
        logger.info("An ai-generated PR is already open. Skipping to avoid stacking PRs.")
        return state

    branch_name = state["branch_name"]

    # Create branch
    result = run_shell(f"git checkout -b {branch_name}")
    if result.returncode != 0:
        return {**state, "errors": state["errors"] + [f"git checkout failed: {result.stderr}"]}

    # Stage files
    files = " ".join(state["generated_files"])
    result = run_shell(f"git add {files}")
    if result.returncode != 0:
        return {**state, "errors": state["errors"] + [f"git add failed: {result.stderr}"]}

    # Build commit message
    target_files = [t.file_path for t in state["targets"]]
    generated_count = len(state["generated_files"])
    provider = state["provider"]
    commit_message = (
        f"Add AI-generated tests for {generated_count} files\n\n"
        f"Coverage targets: {', '.join(target_files)}\n"  # pylint: disable=inconsistent-quotes
        f"Generated by: coverage-agent pipeline (provider: {provider})"
    )

    result = run_shell(f"git commit -m \"{commit_message}\"")
    if result.returncode != 0:
        return {**state, "errors": state["errors"] + [f"git commit failed: {result.stderr}"]}

    # Push
    result = run_shell(f"git push -u origin {branch_name}")
    if result.returncode != 0:
        return {**state, "errors": state["errors"] + [f"git push failed: {result.stderr}"]}

    # Create PR
    pr_title = f"[coverage-agent] Add tests for {generated_count} files"
    pr_body = (
        "## Summary\n\n"
        f"AI-generated tests targeting {generated_count} files with low coverage.\n\n"
        "## Files tested\n\n"
        + "\n".join(f"- `{f}`" for f in state["generated_files"])
        + "\n\n"
        "## Quality gate\n\n"
        "All generated tests passed the SWE best practices quality gate:\n"
        "- Meaningful assertions\n"
        "- Tests public API only\n"
        "- No logic in test bodies\n"
        "- Deterministic\n"
        "- Lint passes\n\n"
        "---\n"
        "Generated by coverage-agent pipeline"
    )

    result = run_shell(
        f"gh pr create --title \"{pr_title}\" --body \"{pr_body}\" --label ai-generated"
    )
    if result.returncode != 0:
        # Label might not exist yet
        if "label" in result.stderr.lower():
            run_shell("gh label create ai-generated --description \"AI-generated PR\" --color 7057ff")
            result = run_shell(
                f"gh pr create --title \"{pr_title}\" --body \"{pr_body}\" --label ai-generated"
            )

    pr_url = result.stdout.strip() if result.returncode == 0 else None
    errors = list(state["errors"])
    if result.returncode != 0:
        errors.append(f"gh pr create failed: {result.stderr}")

    return {**state, "pr_url": pr_url, "errors": errors}
