//SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at

//http://www.apache.org/licenses/LICENSE-2.0

//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

//SPDX-License-Identifier: Apache-2.0
import { type TaskListResponse, type TaskSummaryListItem } from "~/models/tasks-model";

export const MOCK_TASK_LIST_RESPONSE: TaskListResponse = {
  tasks: [
    {
      user: "yuezhao@nvidia.com",
      workflow_id: "legion_training-783",
      workflow_uuid: "19ed7f8203fc40cd8a0c29ab15178184",
      task_name: "training_task",
      pool: "legion_pool",
      node: "legion_node",
      start_time: null,
      end_time: null,
      duration: null,
      status: "WAITING",
      overview: "https://us-west-2-aws.osmo.nvidia.com/api/workflow/legion_training-783",
      logs: "https://us-west-2-aws.osmo.nvidia.com/api/workflow/legion_training-783/logs?task_name=training_task",
      error_logs: null,
      grafana_url: "https://us-west-2-aws.osmo.nvidia.com/grafana/d/HExS-0HVk/workflow-resources?var-namespace=osmo-prod&var-uuid=19ed7f8203fc40cd&from=now-24h&to=now",
      dashboard_url: "https://dgx-h100-02.osmo.nvidia.com/dashboard/#/search?namespace=osmo-prod&q=19ed7f8203fc40cd",
      storage: 100,
      cpu: 8,
      memory: 32,
      gpu: 4,
      priority: "NORMAL",
      retry_id: 0,
    },
    {
      user: "ethany@nvidia.com",
      workflow_id: "serial-workflow-6w2yvz2dancshn3cvjgm7b7lcy",
      workflow_uuid: "5ccavqt5bnbwteb2rk4jk2koey",
      task_name: "serial_task_1",
      pool: "serial_pool",
      node: "serial_node",
      start_time: "2023-12-01T20:38:03.273159",
      end_time: "2023-12-01T20:55:55.090465",
      duration: 1071.817306,
      status: "COMPLETED",
      overview: "https://stg2.osmo.nvidia.com:443/workflows/serial-workflow-6w2yvz2dancshn3cvjgm7b7lcy",
      logs: "https://stg2.osmo.nvidia.com:443/api/workflow/serial-workflow-6w2yvz2dancshn3cvjgm7b7lcy/logs?task_name=serial_task_1",
      error_logs: null,
      grafana_url: "https://isaac-hil-control.nvidia.com/grafana/d/HExS-0HVk/workflow-resources?var-namespace=osmo-staging&var-uuid=5ccavqt5bnbwteb2rk4jk2koey&from=now-431h&to=now-430h",
      dashboard_url: "https://isaac-hil-control.nvidia.com/dashboard/#/search?namespace=_all&q=ia4tatat7nfchovhwaipd7o7hy",
      storage: 50,
      cpu: 4,
      memory: 16,
      gpu: 0,
      priority: "NORMAL",
      retry_id: 0,
    },
    {
      user: "ethany@nvidia.com",
      workflow_id: "serial-workflow-huzwwkh4rranrbpah75olrd6am",
      workflow_uuid: "5ccavqt5bnbwteb2rk4jk2koey",
      task_name: "serial_task_2",
      pool: "serial_pool",
      node: "serial_node",
      start_time: "2023-10-28T00:19:15.421701",
      end_time: "2023-10-28T00:19:15.888500",
      duration: 0.466799,
      status: "FAILED_SERVER_ERROR",
      overview: "https://stg2.osmo.nvidia.com:443/workflows/serial-workflow-huzwwkh4rranrbpah75olrd6am",
      logs: "https://stg2.osmo.nvidia.com:443/api/workflow/serial-workflow-huzwwkh4rranrbpah75olrd6am/logs?task_name=serial_task_2",
      error_logs: "https://stg2.osmo.nvidia.com:443/api/workflow/serial-workflow-huzwwkh4rranrbpah75olrd6am/error_logs?task_name=serial_task_2",
      grafana_url: "https://isaac-hil-control.nvidia.com/grafana/d/HExS-0HVk/workflow-resources?var-namespace=osmo-staging&var-uuid=5ccavqt5bnbwteb2rk4jk2koey&from=now-431h&to=now-430h",
      dashboard_url: "https://isaac-hil-control.nvidia.com/dashboard/#/search?namespace=_all&q=ia4tatat7nfchovhwaipd7o7hy",
      storage: 25,
      cpu: 2,
      memory: 8,
      gpu: 0,
      priority: "NORMAL",
      retry_id: 0,
    },
    {
      user: "test@nvidia.com",
      workflow_id: "stereo_image_proc_graph-krkfgxdtlzgqjkfgkuixudoq5i",
      workflow_uuid: "krkfgxdtlzgqjkfgkuixudoq5i",
      task_name: "stereo_processing",
      pool: "stereo_pool",
      node: "stereo_image_proc_graph",
      start_time: "2023-11-30T09:11:20.202510",
      end_time: "2023-11-30T09:15:18.274550",
      duration: 238.07204,
      status: "COMPLETED",
      overview: "https://us-west-2-aws.osmo.nvidia.com/api/workflow/stereo_image_proc_graph-krkfgxdtlzgqjkfgkuixudoq5i",
      logs: "https://us-west-2-aws.osmo.nvidia.com/api/workflow/stereo_image_proc_graph-krkfgxdtlzgqjkfgkuixudoq5i/logs?task_name=stereo_processing",
      error_logs: null,
      grafana_url: "https://isaac-hil-control.nvidia.com/grafana/d/HExS-0HVk/workflow-resources?var-namespace=osmo-staging&var-uuid=krkfgxdtlzgqjkfgkuixudoq5i&from=now-431h&to=now-430h",
      dashboard_url: "https://isaac-hil-control.nvidia.com/dashboard/#/search?namespace=_all&q=krkfgxdtlzgqjkfgkuixudoq5i",
      storage: 200,
      cpu: 16,
      memory: 64,
      gpu: 2,
      priority: "HIGH",
      retry_id: 0,
    },
    {
      user: "svc-osmo-admin@nvidia.com",
      workflow_id: "isaac_ros_bi3d_fs_node-yeiq3vcxwnealkgxxfnmbma6eq",
      workflow_uuid: "yeiq3vcxwnealkgxxfnmbma6eq",
      task_name: "bi3d_processing",
      pool: "isaac_pool",
      node: "isaac_ros_bi3d_fs_node",
      start_time: "2023-11-30T12:09:55.581388",
      end_time: "2023-11-30T12:14:34.636916",
      duration: 279.055528,
      status: "COMPLETED",
      overview: "https://us-west-2-aws.osmo.nvidia.com/api/workflow/isaac_ros_bi3d_fs_node-yeiq3vcxwnealkgxxfnmbma6eq",
      logs: "https://us-west-2-aws.osmo.nvidia.com/api/workflow/isaac_ros_bi3d_fs_node-yeiq3vcxwnealkgxxfnmbma6eq/logs?task_name=bi3d_processing",
      error_logs: null,
      grafana_url: "https://isaac-hil-control.nvidia.com/grafana/d/HExS-0HVk/workflow-resources?var-namespace=osmo-staging&var-uuid=yeiq3vcxwnealkgxxfnmbma6eq&from=now-431h&to=now-430h",
      dashboard_url: "https://isaac-hil-control.nvidia.com/dashboard/#/search?namespace=_all&q=yeiq3vcxwnealkgxxfnmbma6eq",
      storage: 150,
      cpu: 12,
      memory: 48,
      gpu: 1,
      priority: "NORMAL",
      retry_id: 0,
    },
    {
      user: "cole@nvidia.com",
      workflow_id: "isaac_ros_disparity_node-f7i3zcc7xfaetgfvvgqpwncpsm",
      workflow_uuid: "f7i3zcc7xfaetgfvvgqpwncpsm",
      task_name: "disparity_computation",
      pool: "isaac_pool",
      node: "isaac_ros_disparity_node",
      start_time: "2023-11-30T09:19:11.281086",
      end_time: "2023-11-30T09:23:11.563105",
      duration: 240.282019,
      status: "FAILED",
      overview: "https://us-west-2-aws.osmo.nvidia.com/api/workflow/isaac_ros_disparity_node-f7i3zcc7xfaetgfvvgqpwncpsm",
      logs: "https://us-west-2-aws.osmo.nvidia.com/api/workflow/isaac_ros_disparity_node-f7i3zcc7xfaetgfvvgqpwncpsm/logs?task_name=disparity_computation",
      error_logs: "https://us-west-2-aws.osmo.nvidia.com/api/workflow/isaac_ros_disparity_node-f7i3zcc7xfaetgfvvgqpwncpsm/error_logs?task_name=disparity_computation",
      grafana_url: "https://isaac-hil-control.nvidia.com/grafana/d/HExS-0HVk/workflow-resources?var-namespace=osmo-staging&var-uuid=f7i3zcc7xfaetgfvvgqpwncpsm&from=now-431h&to=now-430h",
      dashboard_url: "https://isaac-hil-control.nvidia.com/dashboard/#/search?namespace=_all&q=f7i3zcc7xfaetgfvvgqpwncpsm",
      storage: 100,
      cpu: 8,
      memory: 32,
      gpu: 1,
      priority: "NORMAL",
      retry_id: 0,
    },
    {
      user: "ethany@nvidia.com",
      workflow_id: "some_test_workflow",
      workflow_uuid: "test_uuid_12345",
      task_name: "test_task",
      pool: "test_pool",
      node: "some_test_node",
      start_time: "2023-11-30T09:19:11.281086",
      end_time: null,
      duration: null,
      status: "RUNNING",
      overview: "https://us-west-2-aws.osmo.nvidia.com/api/workflow/some_test_workflow",
      logs: "https://us-west-2-aws.osmo.nvidia.com/api/workflow/some_test_workflow/logs?task_name=test_task",
      error_logs: null,
      grafana_url: "https://isaac-hil-control.nvidia.com/grafana/d/HExS-0HVk/workflow-resources?var-namespace=osmo-staging&var-uuid=test_uuid_12345&from=now-431h&to=now-430h",
      dashboard_url: "https://isaac-hil-control.nvidia.com/dashboard/#/search?namespace=_all&q=test_uuid_12345",
      storage: 75,
      cpu: 6,
      memory: 24,
      gpu: 0,
      priority: "LOW",
      retry_id: 0,
    },
    {
      user: "atanas@nvidia.com",
      workflow_id: "isaac_ros_triton_ps_node-myvltkp5zrcf3cne5zb2jljapq",
      workflow_uuid: "myvltkp5zrcf3cne5zb2jljapq",
      task_name: "triton_inference",
      pool: "isaac_pool",
      node: "isaac_ros_triton_ps_node",
      start_time: "2023-11-30T09:16:21.840066",
      end_time: "2023-11-30T09:26:26.872038",
      duration: 605.031972,
      status: "COMPLETED",
      overview: "https://us-west-2-aws.osmo.nvidia.com/api/workflow/isaac_ros_triton_ps_node-myvltkp5zrcf3cne5zb2jljapq",
      logs: "https://us-west-2-aws.osmo.nvidia.com/api/workflow/isaac_ros_triton_ps_node-myvltkp5zrcf3cne5zb2jljapq/logs?task_name=triton_inference",
      error_logs: null,
      grafana_url: "https://isaac-hil-control.nvidia.com/grafana/d/HExS-0HVk/workflow-resources?var-namespace=osmo-staging&var-uuid=myvltkp5zrcf3cne5zb2jljapq&from=now-431h&to=now-430h",
      dashboard_url: "https://isaac-hil-control.nvidia.com/dashboard/#/search?namespace=_all&q=myvltkp5zrcf3cne5zb2jljapq",
      storage: 300,
      cpu: 20,
      memory: 80,
      gpu: 8,
      priority: "HIGH",
      retry_id: 0,
    },
    {
      user: "alberto@nvidia.com",
      workflow_id: "isaac_ros_apriltag_graph-5ferhfennjeflcny56x7atz63q",
      workflow_uuid: "5ferhfennjeflcny56x7atz63q",
      task_name: "apriltag_detection",
      pool: "isaac_pool",
      node: null,
      start_time: "2023-11-30T10:55:24.083392",
      end_time: "2023-11-30T11:04:29.524003",
      duration: 545.440611,
      status: "COMPLETED",
      overview: "https://us-west-2-aws.osmo.nvidia.com/api/workflow/isaac_ros_apriltag_graph-5ferhfennjeflcny56x7atz63q",
      logs: "https://us-west-2-aws.osmo.nvidia.com/api/workflow/isaac_ros_apriltag_graph-5ferhfennjeflcny56x7atz63q/logs?task_name=apriltag_detection",
      error_logs: null,
      grafana_url: "https://isaac-hil-control.nvidia.com/grafana/d/HExS-0HVk/workflow-resources?var-namespace=osmo-staging&var-uuid=5ferhfennjeflcny56x7atz63q&from=now-431h&to=now-430h",
      dashboard_url: "https://isaac-hil-control.nvidia.com/dashboard/#/search?namespace=_all&q=5ferhfennjeflcny56x7atz63q",
      storage: 120,
      cpu: 10,
      memory: 40,
      gpu: 2,
      priority: "NORMAL",
      retry_id: 0,
    },
    {
      user: "svc-osmo-admin@nvidia.com",
      workflow_id: "image_transport_h264_decoder_node-2enatlrf7bf3nchqweipj54v2i",
      workflow_uuid: "2enatlrf7bf3nchqweipj54v2i",
      task_name: "h264_decoding",
      pool: "isaac_pool",
      node: null,
      start_time: "2023-11-30T12:00:15.604917",
      end_time: "2023-11-30T12:03:46.136278",
      duration: 210.531361,
      status: "COMPLETED",
      overview: "https://us-west-2-aws.osmo.nvidia.com/api/workflow/image_transport_h264_decoder_node-2enatlrf7bf3nchqweipj54v2i",
      logs: "https://us-west-2-aws.osmo.nvidia.com/api/workflow/image_transport_h264_decoder_node-2enatlrf7bf3nchqweipj54v2i/logs?task_name=h264_decoding",
      error_logs: null,
      grafana_url: "https://isaac-hil-control.nvidia.com/grafana/d/HExS-0HVk/workflow-resources?var-namespace=osmo-staging&var-uuid=2enatlrf7bf3nchqweipj54v2i&from=now-431h&to=now-430h",
      dashboard_url: "https://isaac-hil-control.nvidia.com/dashboard/#/search?namespace=_all&q=2enatlrf7bf3nchqweipj54v2i",
      storage: 80,
      cpu: 6,
      memory: 24,
      gpu: 0,
      priority: "NORMAL",
      retry_id: 0,
    },
    {
      user: "svc-osmo-admin@nvidia.com",
      workflow_id: "isaac_ros_h264_decoder_node-ihqlsuyvpzhwdj7kc3rhxyspwe",
      workflow_uuid: "ihqlsuyvpzhwdj7kc3rhxyspwe",
      task_name: "h264_decoder_task",
      pool: "isaac_pool",
      node: null,
      start_time: null,
      end_time: null,
      duration: null,
      status: "WAITING",
      overview: "https://us-west-2-aws.osmo.nvidia.com/api/workflow/isaac_ros_h264_decoder_node-ihqlsuyvpzhwdj7kc3rhxyspwe",
      logs: "https://us-west-2-aws.osmo.nvidia.com/api/workflow/isaac_ros_h264_decoder_node-ihqlsuyvpzhwdj7kc3rhxyspwe/logs?task_name=h264_decoder_task",
      error_logs: null,
      grafana_url: "https://isaac-hil-control.nvidia.com/grafana/d/HExS-0HVk/workflow-resources?var-namespace=osmo-staging&var-uuid=ihqlsuyvpzhwdj7kc3rhxyspwe&from=now-431h&to=now-430h",
      dashboard_url: "https://isaac-hil-control.nvidia.com/dashboard/#/search?namespace=_all&q=ihqlsuyvpzhwdj7kc3rhxyspwe",
      storage: 60,
      cpu: 4,
      memory: 16,
      gpu: 0,
      priority: "LOW",
      retry_id: 0,
    },
    {
      user: "svc-osmo-admin@nvidia.com",
      workflow_id: "isaac_ros_nvblox_node-m2ocrrxll5hrtjihldspp3rb6i",
      workflow_uuid: "m2ocrrxll5hrtjihldspp3rb6i",
      task_name: "nvblox_mapping",
      pool: "isaac_pool",
      node: null,
      start_time: "2023-11-30T12:03:08.881411",
      end_time: "2023-11-30T12:05:28.937639",
      duration: 140.056228,
      status: "COMPLETED",
      overview: "https://us-west-2-aws.osmo.nvidia.com/api/workflow/isaac_ros_nvblox_node-m2ocrrxll5hrtjihldspp3rb6i",
      logs: "https://us-west-2-aws.osmo.nvidia.com/api/workflow/isaac_ros_nvblox_node-m2ocrrxll5hrtjihldspp3rb6i/logs?task_name=nvblox_mapping",
      error_logs: null,
      grafana_url: "https://isaac-hil-control.nvidia.com/grafana/d/HExS-0HVk/workflow-resources?var-namespace=osmo-staging&var-uuid=m2ocrrxll5hrtjihldspp3rb6i&from=now-431h&to=now-430h",
      dashboard_url: "https://isaac-hil-control.nvidia.com/dashboard/#/search?namespace=_all&q=m2ocrrxll5hrtjihldspp3rb6i",
      storage: 250,
      cpu: 18,
      memory: 72,
      gpu: 4,
      priority: "HIGH",
      retry_id: 0,
    },
    {
      user: "svc-osmo-admin@nvidia.com",
      workflow_id: "isaac_ros_visual_slam_node-d2xmoxkoa5fzrhf3jqcacd6ica",
      workflow_uuid: "d2xmoxkoa5fzrhf3jqcacd6ica",
      task_name: "visual_slam",
      pool: "isaac_pool",
      node: null,
      start_time: "2023-11-30T10:04:32.717718",
      end_time: "2023-11-30T10:22:23.791684",
      duration: 1071.073966,
      status: "COMPLETED",
      overview: "https://us-west-2-aws.osmo.nvidia.com/api/workflow/isaac_ros_visual_slam_node-d2xmoxkoa5fzrhf3jqcacd6ica",
      logs: "https://us-west-2-aws.osmo.nvidia.com/api/workflow/isaac_ros_visual_slam_node-d2xmoxkoa5fzrhf3jqcacd6ica/logs?task_name=visual_slam",
      error_logs: null,
      grafana_url: "https://isaac-hil-control.nvidia.com/grafana/d/HExS-0HVk/workflow-resources?var-namespace=osmo-staging&var-uuid=d2xmoxkoa5fzrhf3jqcacd6ica&from=now-431h&to=now-430h",
      dashboard_url: "https://isaac-hil-control.nvidia.com/dashboard/#/search?namespace=_all&q=d2xmoxkoa5fzrhf3jqcacd6ica",
      storage: 400,
      cpu: 24,
      memory: 96,
      gpu: 6,
      priority: "HIGH",
      retry_id: 0,
    },
    {
      user: "svc-osmo-admin@nvidia.com",
      workflow_id: "isaac_ros_disparity_graph-m2254iaqjncztavdjesbm4ujzq",
      workflow_uuid: "m2254iaqjncztavdjesbm4ujzq",
      task_name: "disparity_graph",
      pool: "isaac_pool",
      node: null,
      start_time: null,
      end_time: null,
      duration: null,
      status: "WAITING",
      overview: "https://us-west-2-aws.osmo.nvidia.com/api/workflow/isaac_ros_disparity_graph-m2254iaqjncztavdjesbm4ujzq",
      logs: "https://us-west-2-aws.osmo.nvidia.com/api/workflow/isaac_ros_disparity_graph-m2254iaqjncztavdjesbm4ujzq/logs?task_name=disparity_graph",
      error_logs: null,
      grafana_url: "https://isaac-hil-control.nvidia.com/grafana/d/HExS-0HVk/workflow-resources?var-namespace=osmo-staging&var-uuid=m2254iaqjncztavdjesbm4ujzq&from=now-431h&to=now-430h",
      dashboard_url: "https://isaac-hil-control.nvidia.com/dashboard/#/search?namespace=_all&q=m2254iaqjncztavdjesbm4ujzq",
      storage: 180,
      cpu: 14,
      memory: 56,
      gpu: 3,
      priority: "NORMAL",
      retry_id: 0,
    },
    {
      user: "svc-osmo-admin@nvidia.com",
      workflow_id: "isaac_ros_bi3d_fs_node-ingkvee6rjaoxbymp22neen5fu",
      workflow_uuid: "ingkvee6rjaoxbymp22neen5fu",
      task_name: "bi3d_fs_processing",
      pool: "isaac_pool",
      node: null,
      start_time: "2023-11-30T11:54:50.384679",
      end_time: "2023-11-30T12:00:09.491615",
      duration: 319.106936,
      status: "COMPLETED",
      overview: "https://us-west-2-aws.osmo.nvidia.com/api/workflow/isaac_ros_bi3d_fs_node-ingkvee6rjaoxbymp22neen5fu",
      logs: "https://us-west-2-aws.osmo.nvidia.com/api/workflow/isaac_ros_bi3d_fs_node-ingkvee6rjaoxbymp22neen5fu/logs?task_name=bi3d_fs_processing",
      error_logs: null,
      grafana_url: "https://isaac-hil-control.nvidia.com/grafana/d/HExS-0HVk/workflow-resources?var-namespace=osmo-staging&var-uuid=ingkvee6rjaoxbymp22neen5fu&from=now-431h&to=now-430h",
      dashboard_url: "https://isaac-hil-control.nvidia.com/dashboard/#/search?namespace=_all&q=ingkvee6rjaoxbymp22neen5fu",
      storage: 160,
      cpu: 12,
      memory: 48,
      gpu: 2,
      priority: "NORMAL",
      retry_id: 0,
    },
    {
      user: "svc-osmo-admin@nvidia.com",
      workflow_id: "stereo_image_proc_graph-5e5xbvrwlfg23doqk5ousnpzou",
      workflow_uuid: "5e5xbvrwlfg23doqk5ousnpzou",
      task_name: "stereo_image_processing",
      pool: "isaac_pool",
      node: null,
      start_time: "2023-11-30T10:04:21.532960",
      end_time: "2023-11-30T10:08:30.442958",
      duration: 248.909998,
      status: "COMPLETED",
      overview: "https://us-west-2-aws.osmo.nvidia.com/api/workflow/stereo_image_proc_graph-5e5xbvrwlfg23doqk5ousnpzou",
      logs: "https://us-west-2-aws.osmo.nvidia.com/api/workflow/stereo_image_proc_graph-5e5xbvrwlfg23doqk5ousnpzou/logs?task_name=stereo_image_processing",
      error_logs: null,
      grafana_url: "https://isaac-hil-control.nvidia.com/grafana/d/HExS-0HVk/workflow-resources?var-namespace=osmo-staging&var-uuid=5e5xbvrwlfg23doqk5ousnpzou&from=now-431h&to=now-430h",
      dashboard_url: "https://isaac-hil-control.nvidia.com/dashboard/#/search?namespace=_all&q=5e5xbvrwlfg23doqk5ousnpzou",
      storage: 140,
      cpu: 10,
      memory: 40,
      gpu: 1,
      priority: "NORMAL",
      retry_id: 0,
    },
    {
      user: "svc-osmo-admin@nvidia.com",
      workflow_id: "isaac_ros_h264_encoder_iframe_node-jdj55eyojjcjfdpjbou22gi4x4",
      workflow_uuid: "jdj55eyojjcjfdpjbou22gi4x4",
      task_name: "h264_encoding",
      pool: "isaac_pool",
      node: null,
      start_time: "2023-11-30T11:52:07.889970",
      end_time: "2023-11-30T11:54:45.936867",
      duration: 158.046897,
      status: "COMPLETED",
      overview: "https://us-west-2-aws.osmo.nvidia.com/api/workflow/isaac_ros_h264_encoder_iframe_node-jdj55eyojjcjfdpjbou22gi4x4",
      logs: "https://us-west-2-aws.osmo.nvidia.com/api/workflow/isaac_ros_h264_encoder_iframe_node-jdj55eyojjcjfdpjbou22gi4x4/logs?task_name=h264_encoding",
      error_logs: null,
      grafana_url: "https://isaac-hil-control.nvidia.com/grafana/d/HExS-0HVk/workflow-resources?var-namespace=osmo-staging&var-uuid=jdj55eyojjcjfdpjbou22gi4x4&from=now-431h&to=now-430h",
      dashboard_url: "https://isaac-hil-control.nvidia.com/dashboard/#/search?namespace=_all&q=jdj55eyojjcjfdpjbou22gi4x4",
      storage: 90,
      cpu: 6,
      memory: 24,
      gpu: 0,
      priority: "NORMAL",
      retry_id: 0,
    },
    {
      user: "svc-osmo-admin@nvidia.com",
      workflow_id: "image_proc_rectify_node-l6zpve5bfzbujnptvp3r2iscpu",
      workflow_uuid: "l6zpve5bfzbujnptvp3r2iscpu",
      task_name: "image_rectification",
      pool: "isaac_pool",
      node: null,
      start_time: "2023-11-30T11:03:48.402015",
      end_time: "2023-11-30T11:10:01.655018",
      duration: 373.253003,
      status: "COMPLETED",
      overview: "https://us-west-2-aws.osmo.nvidia.com/api/workflow/image_proc_rectify_node-l6zpve5bfzbujnptvp3r2iscpu",
      logs: "https://us-west-2-aws.osmo.nvidia.com/api/workflow/image_proc_rectify_node-l6zpve5bfzbujnptvp3r2iscpu/logs?task_name=image_rectification",
      error_logs: null,
      grafana_url: "https://isaac-hil-control.nvidia.com/grafana/d/HExS-0HVk/workflow-resources?var-namespace=osmo-staging&var-uuid=l6zpve5bfzbujnptvp3r2iscpu&from=now-431h&to=now-430h",
      dashboard_url: "https://isaac-hil-control.nvidia.com/dashboard/#/search?namespace=_all&q=l6zpve5bfzbujnptvp3r2iscpu",
      storage: 70,
      cpu: 4,
      memory: 16,
      gpu: 0,
      priority: "LOW",
      retry_id: 0,
    },
    {
      user: "svc-osmo-admin@nvidia.com",
      workflow_id: "isaac_ros_bi3d_fs_node-eg3wob6zqvegrojqa332y2dm7u",
      workflow_uuid: "eg3wob6zqvegrojqa332y2dm7u",
      task_name: "bi3d_fs_node_task",
      pool: "isaac_pool",
      node: "isaac_ros_bi3d_fs_node",
      start_time: "2023-11-30T09:54:38.168792",
      end_time: "2023-11-30T10:04:16.564580",
      duration: 578.395788,
      status: "COMPLETED",
      overview: "https://us-west-2-aws.osmo.nvidia.com/api/workflow/isaac_ros_bi3d_fs_node-eg3wob6zqvegrojqa332y2dm7u",
      logs: "https://us-west-2-aws.osmo.nvidia.com/api/workflow/isaac_ros_bi3d_fs_node-eg3wob6zqvegrojqa332y2dm7u/logs?task_name=bi3d_fs_node_task",
      error_logs: null,
      grafana_url: "https://isaac-hil-control.nvidia.com/grafana/d/HExS-0HVk/workflow-resources?var-namespace=osmo-staging&var-uuid=eg3wob6zqvegrojqa332y2dm7u&from=now-431h&to=now-430h",
      dashboard_url: "https://isaac-hil-control.nvidia.com/dashboard/#/search?namespace=_all&q=eg3wob6zqvegrojqa332y2dm7u",
      storage: 200,
      cpu: 16,
      memory: 64,
      gpu: 2,
      priority: "NORMAL",
      retry_id: 0,
    },
  ],
};

// Additional mock data for different scenarios
export const MOCK_TASK_LIST_RESPONSE_EMPTY: TaskListResponse = {
  tasks: [],
};

export const MOCK_TASK_LIST_RESPONSE_SINGLE: TaskListResponse = {
  tasks: [
    {
      user: "test@nvidia.com",
      workflow_id: "test-workflow-123",
      workflow_uuid: "test-uuid-123",
      task_name: "single_test_task",
      pool: "test_pool",
      node: "test_node",
      start_time: "2025-01-15T10:00:00.000000",
      end_time: "2025-01-15T10:05:00.000000",
      duration: 300.0,
      status: "COMPLETED",
      overview: "https://test.osmo.nvidia.com/api/workflow/test-workflow-123",
      logs: "https://test.osmo.nvidia.com/api/workflow/test-workflow-123/logs?task_name=single_test_task",
      error_logs: null,
      grafana_url: "https://test.osmo.nvidia.com/grafana/d/test/workflow-resources?var-namespace=test&var-uuid=test-uuid-123&from=now-24h&to=now",
      dashboard_url: "https://test.osmo.nvidia.com/dashboard/#/search?namespace=test&q=test-uuid-123",
      storage: 50,
      cpu: 4,
      memory: 16,
      gpu: 0,
      priority: "NORMAL",
      retry_id: 0,
    },
  ],
};

export const MOCK_TASK_LIST_RESPONSE_FAILED: TaskListResponse = {
  tasks: [
    {
      user: "error@nvidia.com",
      workflow_id: "error-workflow-456",
      workflow_uuid: "error-uuid-456",
      task_name: "failed_task",
      pool: "error_pool",
      node: "error_node",
      start_time: "2025-01-15T09:00:00.000000",
      end_time: "2025-01-15T09:01:00.000000",
      duration: 60.0,
      status: "FAILED_SERVER_ERROR",
      overview: "https://error.osmo.nvidia.com/api/workflow/error-workflow-456",
      logs: "https://error.osmo.nvidia.com/api/workflow/error-workflow-456/logs?task_name=failed_task",
      error_logs: "https://error.osmo.nvidia.com/api/workflow/error-workflow-456/error_logs?task_name=failed_task",
      grafana_url: "https://error.osmo.nvidia.com/grafana/d/error/workflow-resources?var-namespace=error&var-uuid=error-uuid-456&from=now-24h&to=now",
      dashboard_url: "https://error.osmo.nvidia.com/dashboard/#/search?namespace=error&q=error-uuid-456",
      storage: 25,
      cpu: 2,
      memory: 8,
      gpu: 0,
      priority: "LOW",
      retry_id: 0,
    },
  ],
};

// Mock summary list items used by getSummaryList when mock mode is enabled
export const MOCK_TASK_SUMMARY_LIST: TaskSummaryListItem[] = [
  {
    user: "yuezhao@nvidia.com",
    pool: "legion_pool",
    storage: 100,
    cpu: 8,
    memory: 32,
    gpu: 4,
    priority: "NORMAL",
    workflow_id: "legion_training-783",
  },
  {
    user: "ethany@nvidia.com",
    pool: "serial_pool",
    storage: 75,
    cpu: 6,
    memory: 24,
    gpu: 0,
    priority: "LOW",
    workflow_id: "serial-workflow-6w2yvz2dancshn3cvjgm7b7lcy",
  },
  {
    user: "svc-osmo-admin@nvidia.com",
    pool: "isaac_pool",
    storage: 300,
    cpu: 20,
    memory: 80,
    gpu: 8,
    priority: "HIGH",
    workflow_id: "isaac_ros_triton_ps_node-myvltkp5zrcf3cne5zb2jljapq",
  },
  {
    user: "alberto@nvidia.com",
    pool: "isaac_pool",
    storage: 120,
    cpu: 10,
    memory: 40,
    gpu: 2,
    priority: "NORMAL",
    workflow_id: "isaac_ros_apriltag_graph-5ferhfennjeflcny56x7atz63q",
  },
  {
    user: "cole@nvidia.com",
    pool: "isaac_pool",
    storage: 100,
    cpu: 8,
    memory: 32,
    gpu: 1,
    priority: "NORMAL",
    workflow_id: "isaac_ros_disparity_node-f7i3zcc7xfaetgfvvgqpwncpsm",
  },
];
