{{- if and .Values.planes.compute.enabled .Values.services.backendListener.enabled }}
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
{{- $component := .Values.services.backendListener }}
{{- $name := include "osmo.compute.listenerName" . }}
{{- if $component.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "osmo.compute.listenerServiceAccountName" . }}
  namespace: {{ include "osmo.compute.agentNamespace" . }}
  labels:
    {{- include "osmo.component.labels" (dict "root" . "component" "backend-listener") | nindent 4 }}
  {{- with (include "osmo.metadata.annotations" (dict "root" . "annotations" $component.serviceAccount.annotations)) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $component.serviceAccount.automountServiceAccountToken }}
---
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $name }}-events
  namespace: {{ include "osmo.compute.backendNamespace" . }}
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["list", "watch", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $name }}-events
  namespace: {{ include "osmo.compute.backendNamespace" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "osmo.compute.listenerServiceAccountName" . }}
  namespace: {{ include "osmo.compute.agentNamespace" . }}
roleRef:
  kind: Role
  name: {{ $name }}-events
  apiGroup: rbac.authorization.k8s.io
{{- if .Values.compute.enableClusterRoles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $name }}
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["list", "watch", "get"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get"]
{{- if $component.enableNodeLabelUpdate }}
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["patch"]
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $name }}
subjects:
- kind: ServiceAccount
  name: {{ include "osmo.compute.listenerServiceAccountName" . }}
  namespace: {{ include "osmo.compute.agentNamespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ $name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
