{{- if and .Values.planes.compute.enabled .Values.compute.priorityClasses.create }}
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
{{- range .Values.compute.priorityClasses.classes }}
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .name }}
  labels:
    {{- include "osmo.component.labels" (dict "root" $ "component" "compute-priority-class") | nindent 4 }}
  {{- with (include "osmo.metadata.annotations" (dict "root" $)) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
value: {{ .value }}
globalDefault: false
description: {{ .description | quote }}
{{- end }}
{{- end }}
