# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
{{- if eq .Values.secretManagement.mode "external-secrets" }}
{{- range .Values.secretManagement.externalSecrets.items }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  labels:
    app.kubernetes.io/part-of: osmo
spec:
  refreshPolicy: Periodic
  refreshInterval: {{ $.Values.secretManagement.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ $.Values.secretManagement.externalSecrets.secretStoreRef.name }}
    kind: {{ $.Values.secretManagement.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .targetSecretName }}
    creationPolicy: Orphan
    deletionPolicy: Retain
  data:
  {{- toYaml .data | nindent 4 }}
{{- end }}
{{- end }}
