# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
{{- if and .Values.planes.control.enabled .Values.services.worker.enabled }}
{{- $name := include "osmo.component.fullname" (dict "root" . "suffix" "worker") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    {{- include "osmo.component.labels" (dict "root" . "component" "worker") | nindent 4 }}
  {{- with (include "osmo.metadata.annotations" (dict "root" .)) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.services.worker.autoscaling.enabled }}
  replicas: {{ .Values.services.worker.replicas }}
  {{- end }}
  {{- with .Values.services.worker.deploymentStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "osmo.component.selectorLabels" (dict "root" . "component" "worker") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "osmo.pod.labels" (dict "root" . "component" .Values.services.worker "componentName" "worker") | nindent 8 }}
      annotations:
        {{- include "osmo.pod.annotations" (dict "root" . "component" .Values.services.worker) | nindent 8 }}
    spec:
      automountServiceAccountToken: {{ .Values.services.worker.serviceAccount.automountServiceAccountToken }}
      securityContext:
        {{- include "osmo.pod.securityContext" (dict "root" . "component" .Values.services.worker) | nindent 8 }}
      terminationGracePeriodSeconds: {{ include "osmo.pod.terminationGracePeriodSeconds" (dict "root" . "component" .Values.services.worker) }}
      {{- with (include "osmo.pod.affinity" (dict "root" . "component" .Values.services.worker)) }}
      affinity:
        {{- . | nindent 8 }}
      {{- end }}
      {{- with .Values.services.worker.pod.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- include "osmo.pod.topologySpreadConstraints" (dict "root" $ "constraints" . "componentName" "worker") | nindent 8 }}
      {{- end }}
      {{- with (include "osmo.pod.nodeSelector" (dict "root" . "component" .Values.services.worker)) }}
      nodeSelector:
        {{- . | nindent 8 }}
      {{- end }}
      tolerations:
        {{- include "osmo.pod.tolerations" (dict "root" . "component" .Values.services.worker) | nindent 8 }}
      {{- include "osmo.component.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "osmo.component.serviceAccountName" (dict "component" .Values.services.worker "root" . "suffix" "worker") }}
      {{- with .Values.services.worker.pod.initContainers }}
      initContainers:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: {{ $name }}
        image: {{ include "osmo.component.image" (dict "root" . "component" .Values.services.worker) }}
        command:
        - "worker"
        securityContext:
          {{- include "osmo.container.securityContext" (dict "root" . "component" .Values.services.worker) | nindent 10 }}
        ports:
        - name: metrics
          containerPort: 9464
        imagePullPolicy: {{ include "osmo.component.imagePullPolicy" (dict "root" . "component" .Values.services.worker) }}
        args:
        - --metrics_otel_collector_component
        - {{ $name }}
        - --metrics_otel_enable
        - "true"
        - --redis_host
        - {{ include "osmo.valkey.host" . }}
        - --redis_port
        - {{ include "osmo.valkey.port" . | quote }}
        - --redis_db_number
        - {{ include "osmo.valkey.database" . | quote }}
        {{- if eq (include "osmo.valkey.tlsEnabled" .) "true" }}
        - --redis_tls_enable
        - "true"
        {{- end}}
        - --postgres_host
        - {{ .Values.externalDependencies.postgresql.host }}
        - --postgres_port
        - {{ .Values.externalDependencies.postgresql.port | quote }}
        - --postgres_database_name
        - {{ .Values.externalDependencies.postgresql.database}}
        {{- if .Values.secrets.masterEncryptionKey.existingSecret }}
        - --mek_file
        - {{ .Values.secrets.masterEncryptionKey.mountPath }}
        {{- end}}
        {{- if .Values.externalDependencies.postgresql.username }}
        - --postgres_user
        - {{ .Values.externalDependencies.postgresql.username }}
        {{- end }}
        {{- if .Values.logging.enabled }}
        - --log_level
        - {{ .Values.logging.logLevel }}
        - --k8s_log_level
        - {{ .Values.logging.k8sLogLevel }}
        - --log_format
        - {{ .Values.logging.logFormat | default "text" }}
        {{- end }}
        {{- include "osmo.configuration.args" . | nindent 8 }}
        {{- range $arg := .Values.services.worker.extraArgs }}
        - {{ $arg | quote }}
        {{- end }}
        env:
        {{- include "osmo.configuration.env" . | nindent 8 }}
        {{- include "osmo.component.extraEnv" .Values.services.worker | nindent 8 }}
        {{- include "osmo.externalDependencies.connectionSecretEnv" . | nindent 8 }}
        volumeMounts:
        - name: osmo-progress-files
          mountPath: /var/run/osmo
        {{- if .Values.secrets.masterEncryptionKey.existingSecret}}
        - mountPath: {{ .Values.secrets.masterEncryptionKey.mountPath }}
          name: mek-volume
          subPath: mek.yaml
        {{- end }}
        {{- include "osmo.configuration.volumeMounts" . | nindent 8 }}
        {{- include "osmo.externalDependencies.caVolumeMounts" . | nindent 8 }}
        {{- include "osmo.component.extraVolumeMounts" .Values.services.worker | nindent 8 }}
        resources:
        {{- toYaml .Values.services.worker.resources | nindent 10 }}

        # Restart the worker if its been on the same job for 5 minutes
        livenessProbe:
          exec:
            command:
            - progress_check
            - --progress_interval
            - "300"
          failureThreshold: 1
          periodSeconds: 60
          timeoutSeconds: 15

        # Give the container 60 seconds to startup
        {{- with .Values.services.worker.startupProbe }}
        startupProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}

      {{- include "osmo.pod.extraSidecars" .Values.services.worker | nindent 6 }}
      volumes:
        - name: osmo-progress-files
          emptyDir: {}
        {{- include "osmo.pod.extraVolumes" .Values.services.worker | nindent 8 }}
        {{- include "osmo.secrets.mekVolume" . | nindent 8 }}
        {{- include "osmo.configuration.volumes" . | nindent 8 }}
        {{- include "osmo.externalDependencies.caVolumes" . | nindent 8 }}

---

{{- if .Values.services.worker.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $name }}
  labels:
    {{- include "osmo.component.labels" (dict "root" . "component" "worker") | nindent 4 }}
  {{- with (include "osmo.metadata.annotations" (dict "root" .)) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $name }}
  minReplicas: {{ .Values.services.worker.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.services.worker.autoscaling.maxReplicas }}
  {{- with .Values.services.worker.autoscaling.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  metrics:
  {{- if .Values.services.worker.autoscaling.hpaMemoryTarget }}
  - type: ContainerResource
    containerResource:
      name: memory
      container: {{ $name }}
      target:
        type: Utilization
        averageUtilization: {{ .Values.services.worker.autoscaling.hpaMemoryTarget }}
  {{- end }}
  {{- if .Values.services.worker.autoscaling.hpaCpuTarget }}
  - type: ContainerResource
    containerResource:
      name: cpu
      container: {{ $name }}
      target:
        type: Utilization
        averageUtilization: {{ .Values.services.worker.autoscaling.hpaCpuTarget }}
  {{- end }}
  {{- with .Values.services.worker.autoscaling.customMetrics }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
