# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
{{- if and .Values.planes.control.enabled .Values.services.worker.enabled }}
{{- $name := include "osmo.v1.componentName" (dict "root" . "suffix" "worker") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
spec:
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
        {{- include "osmo.v1.pod-default-labels" (dict "root" . "component" .Values.services.worker) | nindent 8 }}
      annotations:
        {{- include "osmo.v1.extra-annotations" (dict "root" . "component" .Values.services.worker) | nindent 8 }}
    spec:
      topologySpreadConstraints:
      {{- range .Values.services.worker.pod.topologySpreadConstraints }}
      - topologyKey: {{.topologyKey }}
        {{- range $key, $value := . }}
        {{- if ne $key "topologyKey" }}
        {{$key}}: {{$value}}
        {{- end }}
        {{- end }}
        labelSelector:
          matchLabels:
            app: {{ $name }}
      {{- end }}
      {{- with (include "osmo.v1.node-selector" (dict "root" . "component" .Values.services.worker)) }}
      nodeSelector:
        {{- . | nindent 8 }}
      {{- end }}
      tolerations:
        {{- include "osmo.v1.tolerations" (dict "root" . "component" .Values.services.worker) | nindent 8 }}
      {{- include "osmo.v1.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "osmo.v1.service-account-name" (dict "component" .Values.services.worker "root" . "suffix" "worker") }}
      {{- with .Values.services.worker.pod.initContainers }}
      initContainers:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: {{ $name }}
        image: {{ include "osmo.v1.image" (dict "root" . "component" .Values.services.worker) }}
        command:
        - "worker"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          runAsNonRoot: true
          runAsUser: 1001
        ports:
        - name: metrics
          containerPort: 9464
        imagePullPolicy: {{ include "osmo.v1.imagePullPolicy" (dict "root" . "component" .Values.services.worker) }}
        args:
        - --metrics_otel_collector_component
        - {{ $name }}
        - --metrics_otel_enable
        - "true"
        - --redis_host
        - {{ .Values.externalDependencies.valkey.host }}
        - --redis_port
        - {{ .Values.externalDependencies.valkey.port | quote }}
        - --redis_db_number
        - {{ .Values.externalDependencies.valkey.database | quote }}
        {{- if .Values.externalDependencies.valkey.tls.enabled }}
        - --redis_tls_enable
        - "true"
        {{- end}}
        - --postgres_host
        - {{ .Values.externalDependencies.postgresql.host }}
        - --postgres_port
        - {{ .Values.externalDependencies.postgresql.port | quote }}
        - --postgres_database_name
        - {{ .Values.externalDependencies.postgresql.database}}
        {{- if .Values.secrets.masterEncryptionKey.existingSecret }}
        - --mek_file
        - {{ .Values.secrets.masterEncryptionKey.mountPath }}
        {{- end}}
        {{- if .Values.externalDependencies.postgresql.username }}
        - --postgres_user
        - {{ .Values.externalDependencies.postgresql.username }}
        {{- end }}
        {{- if .Values.logging.enabled }}
        - --log_level
        - {{ .Values.logging.logLevel }}
        - --k8s_log_level
        - {{ .Values.logging.k8sLogLevel }}
        - --log_format
        - {{ .Values.logging.logFormat | default "text" }}
        {{- end }}
        {{- include "osmo.v1.configmap-args" . | nindent 8 }}
        {{- range $arg := .Values.services.worker.extraArgs }}
        - {{ $arg | quote }}
        {{- end }}
        env:
        {{- include "osmo.v1.configmap-env" . | nindent 8 }}
        {{- include "osmo.v1.extra-env" .Values.services.worker | nindent 8 }}
        {{- include "osmo.v1.connection-secret-env" . | nindent 8 }}
        {{- if or .Values.secrets.masterEncryptionKey.existingSecret .Values.configuration.enabled .Values.services.worker.volumeMounts .Values.externalDependencies.postgresql.tls.enabled .Values.externalDependencies.valkey.tls.enabled }}
        volumeMounts:
        {{- end }}
        {{- if .Values.secrets.masterEncryptionKey.existingSecret}}
        - mountPath: {{ .Values.secrets.masterEncryptionKey.mountPath }}
          name: mek-volume
          subPath: mek.yaml
        {{- end }}
        {{- include "osmo.v1.configmap-volume-mounts" . | nindent 8 }}
        {{- include "osmo.v1.external-ca-volume-mounts" . | nindent 8 }}
        {{- include "osmo.v1.extra-volume-mounts" .Values.services.worker | nindent 8 }}
        resources:
        {{- toYaml .Values.services.worker.resources | nindent 10 }}

        # Restart the worker if its been on the same job for 5 minutes
        livenessProbe:
          exec:
            command:
            - progress_check
            - --progress_interval
            - "300"
          failureThreshold: 1
          periodSeconds: 60
          timeoutSeconds: 15

        # Give the container 60 seconds to startup
        {{- with .Values.services.worker.startupProbe }}
        startupProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}

      {{- include "osmo.v1.extra-sidecars" .Values.services.worker | nindent 6 }}
      volumes:
        {{- include "osmo.v1.extra-volumes" .Values.services.worker | nindent 8 }}
        {{- include "osmo.v1.mek-volume" . | nindent 8 }}
        {{- include "osmo.v1.configmap-volumes" . | nindent 8 }}
        {{- include "osmo.v1.external-ca-volumes" . | nindent 8 }}

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
  annotations:
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $name }}
  minReplicas: {{ .Values.services.worker.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.services.worker.autoscaling.maxReplicas }}
  metrics:
  - type: ContainerResource
    containerResource:
      name: memory
      container: {{ $name }}
      target:
        type: Utilization
        averageUtilization: {{ .Values.services.worker.autoscaling.hpaMemoryTarget }}
  - type: ContainerResource
    containerResource:
      name: cpu
      container: {{ $name }}
      target:
        type: Utilization
        averageUtilization: {{ .Values.services.worker.autoscaling.hpaCpuTarget }}
  {{- with .Values.services.worker.autoscaling.customMetrics }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
